### ISSUE TITLE
cannot import mask from cvat dataset.

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [openvinotoolkit/datumaro#1074]
I try to use dm.Dataset.import_from('./cvat/'+folder, 'cvat') to import a cvat dataset with segmentation masks, but all the masks are missed.

**Comment by vinnamkim** [comment]
Hi @rpl-alan-shangguan 
Thanks for your interests on our project!
As you can see [here](https://github.com/openvinotoolkit/datumaro/blob/develop/docs/source/docs/data-formats/formats/cvat.md), we currently supports the following annotation types:
- Bbox
- Label
- Points
- Polygon
- PolyLine

for the CVAT data format.
We will support the mask type also as soon as possible. If we merge the implementation to the develop, I'll let you know in this thread. Thank you.

**Comment by vinnamkim** [comment]
Hi @rpl-alan-shangguan,
#1078 is merged to resolve this issue. It is available if you install the latest develop. Otherwise, it will be available for `datumaro==1.4.0` which will be published this end of month.

**Comment by rpl-alan-shangguan** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
