### ISSUE TITLE
Datumaro export in YOLO format results in incomplete dataset

### ISSUE THREAD

**Issue by sbruneaudubuc** [openvinotoolkit/datumaro#112]
Hi,

From CVAT, I exported two tasks as datasets using the "datumaro 1.0" format such that I obtain two archives directory "task1.zip" and "task2.zip". My goal is to combine these two datasets into one so that I can feed the resulting dataset to the YOLO framework.

Here are the steps I take from there:
1. Unpacked the two archives folder generated from the CVAT export (resulting in the directories "task1" and "task2");
2. Created a datumaro project:
```bash
datum create -o proj
```
3. Added the two sources to the datumaro project:
```bash
datum add path -p proj -f datumaro task1
datum add path -p proj -f datumaro task2
```
4. Exported from the darumaro project to the YOLO format:
```bash
datum export -p proj -f yolo -- --save-images
```
As a result, a directory is created with what seems to be the files and format expected by the YOLO framework, but for some reason, it only contains part of the data, here the annotations and images from "task1".

I would expect the output directory to contain the complete dataset, which is here the annotations and images from "task1" and from "task2".

**Comment by zhiltsov-max** [comment]
Hi, please check if tasks have the same image filenames, this can happen if
they were created from video. In such case try to do 'datum transform -t
rename / reindex' and join resulting projects.

пт, 19 февр. 2021 г., 2:42 Samuel Bruneau-Dubuc <notifications@github.com>:

**Comment by sbruneaudubuc** [comment]
Note that the image files in both the directories "task1" and "task2" have the same naming patern, which is "frame_N.png", where N is incrementing from 0 to the last frame number. To illustrate that, here is an example of "task1" and "task2" directory structure:
```
task1                                                                 task2
├── cvat                                                              ├── cvat
│   └── ... some stuff ...                                            │   └── ... some stuff ...
├── dataset                                                           ├── dataset
│   ├── annotations                                                   │   ├── annotations
│   │   └── default.json                                              │   │   └── default.json
│   └── images                                                        │   └── images
│       ├── frame_000000.PNG                                          │       ├── frame_000000.PNG
│       ├── frame_000001.PNG                                          │       ├── frame_000001.PNG
│       ├── frame_000002.PNG                                          │       ├── frame_000002.PNG
│       └── frame_000003.PNG                                          ├── .datumaro
├── .datumaro                                                         │       └── config.yaml
│       └── config.yaml
```
As you can see, "task1" contains 4 images and "task2" contains 3 images. After adding these two sources to a datumaro project and exporting to the YOLO format, the expected result would be that the output dataset contains all the images from "task1" and "task2" for a total of 7 images, which is not the case (I only have the 4 images from "task1").

I found out by looking at the implementation (see reference below) that in a scenario like the one described above, the items in "task2" that are already existing in "task1" are not added to the resulting dataset.

The problem also seems related to a "subset" element that in this case have the same value ("default") for both "task1" and "task2".

https://github.com/openvinotoolkit/datumaro/blob/1325eef27b7478b4e474ad56a53a6552f57dcba4/datumaro/components/project.py#L72-L93

**Comment by sbruneaudubuc** [comment]
@zhiltsov-max, I saw you just posted an answer right before I published. Your answer seems like what I am looking for. I will try that and report back. Thanks!

**Comment by sbruneaudubuc** [comment]
Thanks to @zhiltsov-max, your input helped me finalise what I wanted to do.

For anyone interested in the future, here is the detail of the commands I used (all commands are executed from the directory that contains the exported data from CVAT):

```bash

# Rename the data files contained in task1 and task2 so their names do not overlap (rename starting from "0" for files in task1 and starting from "4" for files in task2)
datum transform -t reindex -p task1 -o task1_reindex -- -s 0
datum transform -t reindex -p task2 -o task2_reindex -- -s 4

# Create a new datumaro project to join both task1 and task2 data files
datum create -o proj
datum add path -p proj -f datumaro task1_reindex
datum add path -p proj -f datumaro task2_reindex

# Verify that the number of files contained in the unified project correspond to the sum of both tasks
datum info -p proj

# Export the unified project to the desired format (YOLO in this case)
datum export -p proj -f yolo -o proj_yolo -- --save-images
```

This could be generalized in a bash script to build datasets from CVAT export.

However, it would be great to see that kind of workflow integrated within CVAT UI so we can export multiple jobs/tasks/projects into one big dataset ready to feed to the desired framework!

**Comment by zhiltsov-max** [comment]
> However, it would be great to see that kind of workflow integrated within CVAT UI so we can export multiple jobs/tasks/projects into one big dataset ready to feed to the desired framework!

This is going to be solved with Projects, which will allow to join few tasks into a single dataset.
