### ISSUE TITLE
Cvat Docker Build with Error

### ISSUE THREAD

**Issue by Lee4396** [openvinotoolkit/datumaro#1122]
When I try to build Cvat server I got the following error:

[build-image 10/10] RUN DATUMARO_HEADLESS=1 python3 -m pip wheel --no-cache-dir     -r /tmp/requirements/production.txt     -r /tmp/dataset_manifest/requirements.txt     -w /tmp/wheelhouse:
#19 0.942 Collecting git+https://github.com/cvat-ai/datumaro.git@0817144ade1ddc514e182ca1835e322cb9af00a0 (from -r /tmp/requirements/base.txt (line 54))
#19 0.943   Cloning https://github.com/cvat-ai/datumaro.git (to revision 0817144ade1ddc514e182ca1835e322cb9af00a0) to /tmp/pip-req-build-u4jm6fzd
#19 0.946   Running command git clone --filter=blob:none --quiet https://github.com/cvat-ai/datumaro.git /tmp/pip-req-build-u4jm6fzd
#19 2.725   Running command git rev-parse -q --verify 'sha^0817144ade1ddc514e182ca1835e322cb9af00a0'
#19 2.728   Running command git fetch -q https://github.com/cvat-ai/datumaro.git 0817144ade1ddc514e182ca1835e322cb9af00a0
#19 3.140   Running command git checkout -q 0817144ade1ddc514e182ca1835e322cb9af00a0
#19 3.712   Resolved https://github.com/cvat-ai/datumaro.git to commit 0817144ade1ddc514e182ca1835e322cb9af00a0
#19 3.713   Running command git submodule update --init --recursive -q
#19 47.53   Installing build dependencies: started
#19 50.98   Installing build dependencies: finished with status 'done'
#19 50.98   Getting requirements to build wheel: started
#19 51.22   Getting requirements to build wheel: finished with status 'done'
#19 51.22   Preparing metadata (pyproject.toml): started
#19 51.48   Preparing metadata (pyproject.toml): finished with status 'done'
#19 51.77 Collecting attrs==21.4.0
#19 52.04   Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
#19 52.17      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 536.1 kB/s eta 0:00:00
#19 52.25 Collecting click==8.1.3
#19 52.30   Downloading click-8.1.3-py3-none-any.whl (96 kB)
#19 52.35      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 1.9 MB/s eta 0:00:00
#19 52.57 Collecting Django==3.2.18
#19 52.62   Downloading Django-3.2.18-py3-none-any.whl (7.9 MB)
#19 53.15      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 14.8 MB/s eta 0:00:00
#19 53.27 Collecting django-appconf==1.0.4
#19 53.31   Downloading django_appconf-1.0.4-py2.py3-none-any.whl (6.3 kB)
#19 53.39 Collecting django-auth-ldap==2.2.0
#19 53.43   Downloading django_auth_ldap-2.2.0-py3-none-any.whl (20 kB)
#19 53.49 Collecting django-compressor==2.4
#19 53.53   Downloading django_compressor-2.4-py2.py3-none-any.whl (126 kB)
#19 53.53      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.1/126.1 KB 200.1 MB/s eta 0:00:00
#19 53.58 Collecting django-allauth>=0.52.0
#19 53.62   Downloading django-allauth-0.54.0.tar.gz (737 kB)
#19 53.65      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 737.1/737.1 KB 31.0 MB/s eta 0:00:00
#19 53.95   Preparing metadata (setup.py): started
#19 54.30   Preparing metadata (setup.py): finished with status 'done'
#19 54.36 Collecting dj-rest-auth[with_social]==2.2.7
#19 54.40   Downloading dj-rest-auth-2.2.7.tar.gz (98 kB)
#19 54.40      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 KB 172.4 MB/s eta 0:00:00
#19 54.45   Preparing metadata (setup.py): started
#19 54.64   Preparing metadata (setup.py): finished with status 'done'
#19 54.69 Collecting django-rq==2.3.2
#19 54.72   Downloading django_rq-2.3.2-py2.py3-none-any.whl (45 kB)
#19 54.73      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 KB 156.6 MB/s eta 0:00:00
#19 54.77 Collecting EasyProcess==0.3
#19 54.79   Downloading EasyProcess-0.3-py2.py3-none-any.whl (7.9 kB)
#19 55.25 Collecting Pillow==9.3.0
#19 55.28   Downloading Pillow-9.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.3 MB)
#19 55.39      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 29.4 MB/s eta 0:00:00
#19 55.87 Collecting numpy==1.22.0
#19 55.90   Downloading numpy-1.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
#19 56.55      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 22.1 MB/s eta 0:00:00
#19 56.66 Collecting python-ldap==3.4.3
#19 56.68   Downloading python-ldap-3.4.3.tar.gz (377 kB)
#19 56.69      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.4/377.4 KB 96.4 MB/s eta 0:00:00
#19 56.94   Installing build dependencies: started
#19 60.05   Installing build dependencies: finished with status 'done'
#19 60.06   Getting requirements to build wheel: started
#19 60.27   Getting requirements to build wheel: finished with status 'done'
#19 60.28   Preparing metadata (pyproject.toml): started
#19 60.50   Preparing metadata (pyproject.toml): finished with status 'done'
#19 60.60 Collecting pytz==2020.1
#19 60.64   Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
#19 60.65      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.2/510.2 KB 60.2 MB/s eta 0:00:00
#19 60.70 Collecting pyunpack==0.2.1
#19 60.73   Downloading pyunpack-0.2.1-py2.py3-none-any.whl (3.7 kB)
#19 60.79 Collecting rcssmin==1.0.6
#19 60.82   Downloading rcssmin-1.0.6.tar.gz (582 kB)
#19 60.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 582.9/582.9 KB 112.8 MB/s eta 0:00:00
#19 60.92   Preparing metadata (setup.py): started
#19 61.12   Preparing metadata (setup.py): finished with status 'done'
#19 61.22 Collecting redis==3.5.3
#19 61.25   Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
#19 61.26      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 KB 178.8 MB/s eta 0:00:00
#19 61.31 Collecting rjsmin==1.1.0
#19 61.35   Downloading rjsmin-1.1.0.tar.gz (412 kB)
#19 61.36      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.4/412.4 KB 57.7 MB/s eta 0:00:00
#19 61.39   Preparing metadata (setup.py): started
#19 61.57   Preparing metadata (setup.py): finished with status 'done'
#19 61.66 Collecting requests==2.26.0
#19 61.69   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
#19 61.69      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 KB 169.1 MB/s eta 0:00:00
#19 61.77 Collecting rq==1.5.2
#19 61.80   Downloading rq-1.5.2-py2.py3-none-any.whl (61 kB)
#19 61.80      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 KB 172.3 MB/s eta 0:00:00
#19 61.84 Collecting rq-scheduler==0.10.0
#19 61.86   Downloading rq_scheduler-0.10.0-py2.py3-none-any.whl (12 kB)
#19 61.89 Collecting sqlparse==0.4.2
#19 61.92   Downloading sqlparse-0.4.2-py3-none-any.whl (42 kB)
#19 61.92      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 KB 151.4 MB/s eta 0:00:00
#19 61.96 Collecting django-sendfile2==0.7.0
#19 61.98   Downloading django_sendfile2-0.7.0-py3-none-any.whl (10 kB)
#19 62.03 Collecting dj-pagination==2.5.0
#19 62.06   Downloading dj_pagination-2.5.0-py3-none-any.whl (36 kB)
#19 62.11 Collecting python-logstash-async==2.5.0
#19 62.14   Downloading python_logstash_async-2.5.0-py2.py3-none-any.whl (22 kB)
#19 62.17 Collecting rules==2.2
#19 62.19   Downloading rules-2.2.tar.gz (53 kB)
#19 62.20      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 KB 159.7 MB/s eta 0:00:00
#19 62.21   Preparing metadata (setup.py): started
#19 62.40   Preparing metadata (setup.py): finished with status 'done'
#19 62.47 Collecting GitPython==3.1.30
#19 62.48   Downloading GitPython-3.1.30-py3-none-any.whl (184 kB)
#19 62.49      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.0/184.0 KB 210.8 MB/s eta 0:00:00
#19 62.53 Collecting coreapi==2.3.3
#19 62.54   Downloading coreapi-2.3.3-py2.py3-none-any.whl (25 kB)
#19 62.58 Collecting django-filter==2.4.0
#19 62.60   Downloading django_filter-2.4.0-py3-none-any.whl (73 kB)
#19 62.61      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 KB 186.4 MB/s eta 0:00:00
#19 62.65 Collecting Markdown==3.2.2
#19 62.68   Downloading Markdown-3.2.2-py3-none-any.whl (88 kB)
#19 62.68      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.0/89.0 KB 183.3 MB/s eta 0:00:00
#19 62.75 Collecting djangorestframework==3.12.4
#19 62.76   Downloading djangorestframework-3.12.4-py3-none-any.whl (957 kB)
#19 62.78      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 957.7/957.7 KB 70.6 MB/s eta 0:00:00
#19 62.83 Collecting Pygments==2.7.4
#19 62.85   Downloading Pygments-2.7.4-py3-none-any.whl (950 kB)
#19 62.87      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 950.1/950.1 KB 65.7 MB/s eta 0:00:00
#19 62.93 Collecting drf-spectacular==0.22.1
#19 62.95   Downloading drf_spectacular-0.22.1-py3-none-any.whl (84 kB)
#19 62.95      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.2/84.2 KB 157.4 MB/s eta 0:00:00
#19 63.17 Collecting Shapely==1.7.1
#19 63.19   Downloading Shapely-1.7.1.tar.gz (383 kB)
#19 63.19      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.2/383.2 KB 185.9 MB/s eta 0:00:00
#19 63.25   Preparing metadata (setup.py): started
#19 63.45   Preparing metadata (setup.py): finished with status 'done'
#19 63.49 Collecting pdf2image==1.14.0
#19 63.50   Downloading pdf2image-1.14.0-py3-none-any.whl (10 kB)
#19 63.71 Collecting opencv-python-headless==4.5.5.62
#19 63.72   Downloading opencv_python_headless-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (47.7 MB)
#19 64.46      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 73.0 MB/s eta 0:00:00
#19 64.72 Collecting h5py==3.6.0
#19 64.74   Downloading h5py-3.6.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
#19 64.80      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 72.5 MB/s eta 0:00:00
#19 64.86 Collecting django-cors-headers==3.5.0
#19 64.88   Downloading django_cors_headers-3.5.0-py3-none-any.whl (11 kB)
#19 64.91 Collecting furl==2.1.0
#19 64.92   Downloading furl-2.1.0-py2.py3-none-any.whl (20 kB)
#19 64.98 Collecting av==9.2.0
#19 64.99   Downloading av-9.2.0.tar.gz (2.4 MB)
#19 65.02      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 75.3 MB/s eta 0:00:00
#19 65.43   Installing build dependencies: started
#19 70.39   Installing build dependencies: finished with status 'done'
#19 70.39   Getting requirements to build wheel: started
#19 73.28   Getting requirements to build wheel: finished with status 'error'
#19 73.29   error: subprocess-exited-with-error
#19 73.29
#19 73.29   × Getting requirements to build wheel did not run successfully.
#19 73.29   │ exit code: 1
#19 73.29   ╰─> [70 lines of output]
#19 73.29       Compiling av/_core.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/_core.pyx
#19 73.29       Compiling av/buffer.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/buffer.pyx
#19 73.29       Compiling av/bytesource.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/bytesource.pyx
#19 73.29       Compiling av/descriptor.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/descriptor.pyx
#19 73.29       Compiling av/dictionary.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/dictionary.pyx
#19 73.29       Compiling av/enum.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/enum.pyx
#19 73.29       Compiling av/error.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/error.pyx
#19 73.29       Compiling av/format.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/format.pyx
#19 73.29       Compiling av/frame.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/frame.pyx
#19 73.29
#19 73.29       Error compiling Cython file:
#19 73.29       ------------------------------------------------------------
#19 73.29       ...
#19 73.29       cdef const char *log_context_name(void *ptr) nogil:
#19 73.29           cdef log_context *obj = <log_context*>ptr
#19 73.29           return obj.name
#19 73.29
#19 73.29       cdef lib.AVClass log_class
#19 73.29       log_class.item_name = log_context_name
#19 73.29                             ^
#19 73.29       ------------------------------------------------------------
#19 73.29
#19 73.29       av/logging.pyx:216:22: Cannot assign type 'const char *(void *) except? NULL nogil' to 'const char *(*)(void *) noexcept nogil'
#19 73.29
#19 73.29       Error compiling Cython file:
#19 73.29       ------------------------------------------------------------
#19 73.29       ...
#19 73.29
#19 73.29       # Start the magic!
#19 73.29       # We allow the user to fully disable the logging system as it will not play
#19 73.29       # nicely with subinterpreters due to FFmpeg-created threads.
#19 73.29       if os.environ.get('PYAV_LOGGING') != 'off':
#19 73.29           lib.av_log_set_callback(log_callback)
#19 73.29                                   ^
#19 73.29       ------------------------------------------------------------
#19 73.29
#19 73.29       av/logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback'
#19 73.29       Compiling av/logging.pyx because it changed.
#19 73.29       [1/1] Cythonizing av/logging.pyx
#19 73.29       Traceback (most recent call last):
#19 73.29         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#19 73.29           main()
#19 73.29         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#19 73.29           json_out['return_val'] = hook(**hook_input['kwargs'])
#19 73.29         File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#19 73.29           return hook(config_settings)
#19 73.29         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
#19 73.29           return self._get_build_requires(
#19 73.29         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
#19 73.29           self.run_setup()
#19 73.29         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
#19 73.29           super(_BuildMetaLegacyBackend,
#19 73.29         File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
#19 73.29           exec(compile(code, __file__, 'exec'), locals())
#19 73.29         File "setup.py", line 157, in <module>
#19 73.29           ext_modules += cythonize(
#19 73.29         File "/tmp/pip-build-env-576_ciis/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
#19 73.29           cythonize_one(*args)
#19 73.29         File "/tmp/pip-build-env-576_ciis/overlay/local/lib/python3.10/dist-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
#19 73.29           raise CompileError(None, pyx_file)
#19 73.29       Cython.Compiler.Errors.CompileError: av/logging.pyx
#19 73.29       [end of output]
#19 73.29
#19 73.29   note: This error originates from a subprocess, and is likely not a problem with pip.
#19 73.29 error: subprocess-exited-with-error
#19 73.29
#19 73.29 × Getting requirements to build wheel did not run successfully.
#19 73.29 │ exit code: 1
#19 73.29 ╰─> See above for output.
#19 73.29
#19 73.29 note: This error originates from a subprocess, and is likely not a problem with pip.

Datumaro tends to give unpredictable errors during cvat docker build

**Comment by vinnamkim** [comment]
Hi @Lee4396,

As you can see these lines in your logs,
```
https://github.com/openvinotoolkit/datumaro/pull/19 0.942 Collecting git+https://github.com/cvat-ai/datumaro.git@0817144ade1ddc514e182ca1835e322cb9af00a0 (from -r /tmp/requirements/base.txt (line 54))
https://github.com/openvinotoolkit/datumaro/pull/19 0.943 Cloning https://github.com/cvat-ai/datumaro.git (to revision https://github.com/openvinotoolkit/datumaro/commit/0817144ade1ddc514e182ca1835e322cb9af00a0) to /tmp/pip-req-build-u4jm6fzd
```

CVAT.ai maintains its own Datumaro forked repository: . https://github.com/cvat-ai/datumaro.git. Would you please raise your issue on that repository?

Sorry for inconvenience.

**Comment by Lee4396** [comment]
> 

Oh, thanks, will do so now
