### ISSUE TITLE
Export coco instances from datumaro format doesn't load annotations

### ISSUE THREAD

**Issue by CahSrv** [openvinotoolkit/datumaro#1147]
Hi guys, i have a problem. 

I need to export annotations in datumaro format to coco instances in the following scenario:

First, annotations are made in cvat 2.6.2 and exported in formamo datumaro 1.0 images. (without saving the media)

![267049476-9288eebf-985e-4179-a4e9-fbe0e89df939](https://github.com/openvinotoolkit/datumaro/assets/106078752/5b2fa059-a658-4f25-a1d4-e50396c0f096)

Then, in Python, after some data processing, the annotations are exported to the coco instances format:

![image](https://github.com/openvinotoolkit/datumaro/assets/106078752/8ea1dc54-8864-46f7-aa51-71825ed2b3ef)

the dataset is exported, but the annotations are empty:

![image](https://github.com/openvinotoolkit/datumaro/assets/106078752/a0a579ce-cdc7-466a-9783-53b860093d6d)

**Temporary solution**

Add media to datumaro item
![image](https://github.com/openvinotoolkit/datumaro/assets/106078752/ea87db4b-a26b-4ddf-8ffd-48b34b8c0037)

Any better solution?

**Comment by CahSrv** [comment]
in short, the annotations are not converted to the new format if there is no media, but the annotations do exist.

**Comment by jihyeonyi** [comment]
Sorry for the late response. I'll take a look. Please wait some more days.
I would appreciate it if you could share which version of datumaro you used in python.

**Comment by CahSrv** [comment]
in python: datumaro==1.2.1

**Comment by jihyeonyi** [comment]
Hi, I've created a similar environment and tested it, but I cannot reproduce the problem.
I've tried convert dataset in cvat format to datumaro / datumaro to coco_instance without saving images.
Would you provide more data so I can reproduce this?

**Comment by jihyeonyi** [comment]
Hi, I'd like to ask something for clarification. I guess you're using Bbox annotations only, don't you?

**Comment by jihyeonyi** [comment]
Thank you for the reporting this issue. I modified coco exporter to deal with this issue. Coco exporter will be able to export annotations which doesn't require media(image) information when there's no media. 
Related PR link: https://github.com/openvinotoolkit/datumaro/pull/1158
