### ISSUE TITLE
Error while Imagenet dataset parsing

### ISSUE THREAD

**Issue by yunchu** [openvinotoolkit/datumaro#1178]
`NotADirectoryError` is occur when parsing dataset path as `imagenet` format if the target folder have the file not the folder.

e.g.,
- flower_photos/
  - daisy/
  - dandelion/
  - LICENSE.txt
  - roses/
  - sunflowers/
  - tulips/

**Comment by wonjuleee** [comment]
Thanks @yunchu, this was resolved through https://github.com/openvinotoolkit/datumaro/pull/1179 and released with `1.5.1` tag. Feel free to enjoy Datumaro :)
