### ISSUE TITLE
The recent nightly failures on the Windows platform

### ISSUE THREAD

**Issue by vinnamkim** [openvinotoolkit/datumaro#1189]
https://github.com/openvinotoolkit/datumaro/actions/runs/6800055459/job/18487758666

We have failed on importing `tensorflow-datasets` correctly. It comes from the upstream issue here https://github.com/tensorflow/datasets/issues/5097.

**Comment by wonjuleee** [comment]
From the issue you attached, it might be available when installing tfds-nightly. Or, we need to wait a new release (maybe `4.9.4`?). What do you prefer?

**Comment by vinnamkim** [comment]
I thought that they (`tfds`) will release the fixed version soon but it seems taking a while. I don't know which one would be the best choice:
1. Just leave it until the new release
2. Modify `requirements.txt` with `tfds<4.9.2` until the new release

Replacing `tfds` with `tfds-nightly` is not preferred for me since the nightly distribution is changed daily, so that it feels me unstable.

**Comment by vinnamkim** [comment]
Fixed in https://github.com/openvinotoolkit/datumaro/pull/1218
