### ISSUE TITLE
Cannot install datumaro

### ISSUE THREAD

**Issue by csvke** [openvinotoolkit/datumaro#1201]
When I run `pip install 'git+https://github.com/openvinotoolkit/datumaro[default]'` in a blank Google Colab Notebook
```
output
Collecting git+https://github.com/openvinotoolkit/datumaro[default]
  Cloning https://github.com/openvinotoolkit/datumaro[default] to /tmp/pip-req-build-s83kv2iv
  Running command git clone --filter=blob:none --quiet 'https://github.com/openvinotoolkit/datumaro[default]' /tmp/pip-req-build-s83kv2iv
  remote: Repository not found.
  fatal: repository 'https://github.com/openvinotoolkit/datumaro[default]/' not found
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet 'https://github.com/openvinotoolkit/datumaro[default]' /tmp/pip-req-build-s83kv2iv did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet 'https://github.com/openvinotoolkit/datumaro[default]' /tmp/pip-req-build-s83kv2iv did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

And if I run `pip install datumaro[default]` in my local machine, it says `zsh: no matches found: datumaro[default]`

**Comment by jihyeonyi** [comment]
Hi,
Thank you for the reporting this issue, and I'm sorry for the late response.
Could you please re-try with the following command?
`pip install 'datumaro[default] @ git+https://github.com/openvinotoolkit/datumaro'`

I'll update the document, too.

**Comment by jihyeonyi** [comment]
Related PR: https://github.com/openvinotoolkit/datumaro/pull/1202
Note that you need to prepare c++ and Rust build system before installing datumaro from github.
Otherwise, you can install datumaro from PyPI (`pip install datumaro[default]`). This is recommended way to install datumaro.

**Comment by jihyeonyi** [comment]
For the zsh issue, zsh uses square brackets for globbing / pattern matching.
So you need to quote the square bracket arguments like this:
`pip install 'datumaro[default]'`

If you want to disable globbing for the pip command permanently, you can do so by adding `alias pip='noglob pip'` to your ~/.zshrc.

**Comment by wonjuleee** [comment]
@csvke, I will close this issue. Thank you for your interests!
