### ISSUE TITLE
Use datum dataset for PyTorch

### ISSUE THREAD

**Issue by CourchesneA** [openvinotoolkit/datumaro#1212]
I would like to use datumaro as a standard dataset format, but in order to use it for pytorch I need to create a pytorch.Dataset wrapper for it. The dataset interface requires to implement the `__getitem__(idx:int)` function, which is not available on a datumaro dataset.

I am currently using [the code](https://github.com/openvinotoolkit/datumaro/pull/1125/files) from datumaro.FrameworkConverter, which keeps a list of item ids in a list and use indexes from this list. However, once it is converted this way, I can no longer use datumaro dataset manipulation utilities such as `split` and `merge`.

Would it be possible to get access to an integer `__getitem__` function directly on the datumaro dataset ?

**Comment by sooahleex** [comment]
Hi @CourchesneA, Sorry for late response.

We plan to incorporate the mentioned `__getitem__` functionality into the Datumaro Dataset. Once this feature is implemented, you will be able to retrieve datasetitem within the dataset using an index as you desire. I will provide further updates once this enhancement is included in the release.

Thank you for your patience and understanding.

**Comment by CourchesneA** [comment]
That is great news. Thanks for the update !

**Comment by wonjuleee** [comment]
Dear @CourchesneA, as following your suggestion, we have implemented random accessing method with `__getitem__` at https://github.com/openvinotoolkit/datumaro/pull/1247. This will be publicly released with Datumaro 2.0 at the mid of March. Sincerely thank you for your continued interests and suggestions.
