### ISSUE TITLE
Split a Dataset into n folds with the transform split function

### ISSUE THREAD

**Issue by DP1701** [openvinotoolkit/datumaro#1242]
Hello everyone, 

I am looking for a way to split a data set into n folds, taking into account the class distribution. The documentation says that this is possible with the function transform split. Now I would like to know if this is also possible with a Python script? 

I am asking this because I have an image dataset (the classes are unbalanced) that I want to perform k-fold cross validation on. I have tried to use the k-fold stratification method, but unfortunately failed. Now I am wondering if I can use the Datumaro method.

**Comment by jihyeonyi** [comment]
Hi @DP1701,
If your task is one of classification, detection, segmentation, or re-id, you can use [task specific splitter](https://github.com/openvinotoolkit/datumaro/blob/eb4435544e410d5e13397e99dff5f4d1ec571cee/src/datumaro/plugins/splitter.py#L28) for your purpose.
You can use `Split` class directly or call `transform('split', ...)`.
Following is pseudo code:
```python
splits = [(f'fold{i}', 0.1) for i in range(10)]
# with transform
dataset = dataset.transform('split', dataset, 'classification', splits) 
subsets = dataset.subsets()

# using Split directly
from datumaro.plugins import Split
splitter = Split(dataset, 'classification', splits)
subsets = splitter.subsets()
```

**Comment by DP1701** [comment]
Hi @jihyeonyi, 
Thanks for the answer but I get the following error message: 

```
transform() takes 2 positional arguments but 5 were given
File "split_test.py", line 11, in <module>
    dataset = dataset.transform('split', dataset, 'detection', splits)
TypeError: transform() takes 2 positional arguments but 5 were given
```

I use this:

```python
from datumaro.components.dataset import Dataset

path_to_dataset = '/Users/user_a/Desktop/dataset'
dataset_format = 'coco_instances'

dataset = Dataset.import_from(path_to_dataset, dataset_format)

splits = [(f'fold{i}', 0.1) for i in range(10)]

# with transform
dataset = dataset.transform('split', dataset, 'detection', splits) 
subsets = dataset.subsets()
```

**Comment by jihyeonyi** [comment]
Hi @DP1701 
Let me correct the transform call like below.
```python
dataset = dataset.transform('split', task='detection', splits=splits)
```

**Comment by jihyeonyi** [comment]
I close this ticket because it seems that your question is resolved.

**Comment by DP1701** [comment]
@jihyeonyi  Sorry I didn't get in touch sooner. Here is a short update. It works wonderfully when I use the following:

``` python
from datumaro.plugins.splitter import Split
...
dataset_format = 'coco_instances'
dataset = Dataset.import_from(path_to_dataset, dataset_format)

k_split_portion = 1.0/k_split
fold_portion = [(f'fold{i}', k_split_portion) for i in range(k_split)]
    
# Create folds
folds = Split(dataset, mode, fold_portion, seed=None)
folds_subsets = folds.subsets()
...
```

I have another question: How can I merge two subsets and export them as coco_instances so that I get one annotation file? 

Currently I have used the following:

```python
...
merge_dataset = Dataset(folds_subsets['fold0'])
subset_two = Dataset(folds_subsets['fold1'])
merge_dataset = merge_dataset.update(subset_two)
subset_one.export(export_path, dataset_format, save_media=True, reindex=True, image_ext='.png')
```

When I run this, I get two json files in the annotations folder and not one json file. 
How could I implement it so that I get one annotation file?

**Comment by jihyeonyi** [comment]
Hi @DP1701, 

I'm happy to hear that you successfully split your dataset.

For the second question, you've got two json files because the coco format generates separated annotation files for each subsets.
To get one annotation file, you need to aggregate subsets into one. Please refer [the document](https://openvinotoolkit.github.io/datumaro/latest/docs/level-up/intermediate_skills/05_data_aggregation.html).

Here is the code example:
```python

from datumaro.components.hl_ops import HLOps
aggregated = HLOps.aggregate(merge_dataset, from_subsets=["fold0", "fold1"], to_subset="train")
aggregated.export(export_path, dataset_format, save_media=True, reindex=True, image_ext='.png')

```

I hope this will help.

**Comment by wonjuleee** [comment]
Thank you for your interests @DP1701. From your report, we felt the need of data preparation for K-fold cross validation. We are going to get back with this feature in the near future. I will close this issue.
