### ISSUE TITLE
DOTA Dataset Format Support in Datumaro

### ISSUE THREAD

**Issue by sh0622-kim** [openvinotoolkit/datumaro#1287]
Dear Datumaro Team,

I'm reaching out to suggest the addition of support for the DOTA (Dataset for Object Detection in Aerial Images) format in Datumaro. This format, which uses Oriented Bounding Boxes (OBB) for annotations, is crucial for projects involving aerial image analysis.

The integration of DOTA would broaden Datumaro’s utility for aerial imagery projects, facilitating dataset management and preprocessing tasks with its OBB-specific needs.

I believe this addition would greatly benefit the community by expanding the tool’s compatibility with popular dataset formats in aerial image processing. Your consideration of this request is greatly appreciated.

Thank you for your hard work and dedication to making Datumaro an excellent tool for the computer vision community.

**Comment by wonjuleee** [comment]
Hi @sh0622-kim, thank you for your interest in Datumaro.
Since the new feature list is frozen for next Datumaro (v2.0.0), we are going to support this format in the 2.1.0 release (maybe around this May)!

**Comment by wonjuleee** [comment]
Hi @sh0622-kim, DOTA format is now available in the develop branch!
Please refer to https://github.com/openvinotoolkit/datumaro/pull/1475 and https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/dota.html

**Comment by sh0622-kim** [comment]
@wonjuleee 
Thank you so much for accepting my request and adding it yourself.
