### ISSUE TITLE
Introduce a stable library API

### ISSUE THREAD

**Issue by zhiltsov-max** [openvinotoolkit/datumaro#133]
Datumaro comes as a command-line tool and as a Python library. While it has a command-line interface, it does not provide a stable an simple to use library API. Such API needs to be documented and tested.

Requirements:
- Ability to use Datumaro functionality with some simple import, such as `import datumaro` or `import datumaro.api`
- Comprehensive documentation for typical use cases
  - Wiki / readthedocs 
- Full documentation for the key entities (`Dataset`, annotation types, etc.)

**Comment by anwar1997ff** [comment]
Hello,
When is the library documentation expected to come out ?

**Comment by zhiltsov-max** [comment]
@anwar1997ff, I can't say about the time estimates, but API documentation is expected to come with API itself, which is planned after the big versioning patch (#26).

**Comment by zhiltsov-max** [comment]
I'll close the issue, because API itself and API and CLI documentation are already added, and all the points are covered.
