### ISSUE TITLE
Dataset filter with python function

### ISSUE THREAD

**Issue by CourchesneA** [openvinotoolkit/datumaro#1379]
I am trying to use the dataset filtering functionnality from this [notebook](https://openvinotoolkit.github.io/datumaro/latest/docs/level-up/intermediate_skills/09_data_filtering.html), but it looks the method overloading is not working and it defaults to an XPath argument.

```
>>> import datumaro as dm
>>> ds = dm.components.dataset.Dataset.import_from('./','datumaro')
>>> def fn(item):
...    return True
>>> filtered_ds = ds.filter(fn)

ERROR:root:Failed to create XPath from expression '<function fn at 0x76f33fd87490>'
ERROR:root:Automatically drop (<class 'datumaro.components.filter.XPathDatasetFilter'>, (), {'xpath': <function fn at 0x76f33fd87490>}) from the transform stack because an error is raised. Therefore, the dataset will not be transformed by this transformation since it is droped.
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.10/site-packages/datumaro/components/dataset_storage.py", line 90, in __init__
    source = transform[0](source, *transform[1], **transform[2])
  File "/home/me/.local/lib/python3.10/site-packages/datumaro/components/filter.py", line 247, in __init__
    xpath = ET.XPath(xpath)
  File "src/lxml/xpath.pxi", line 414, in lxml.etree.XPath.__init__
  File "src/lxml/apihelpers.pxi", line 1539, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'function'

```

Alternatively, I wanted to use the XPath method but it looks like available nodes on items are id, subset, image and annotations, but there isn't one for "attributes", which I can get from the python objects DatasetItems

**Comment by wonjuleee** [comment]
Hi @CourchesneA, thank you for your interests!

When I tested below on release/2.0.0 or develop, it works well.
```code
from datumaro.components.dataset import Dataset

dataset = Dataset.import_from("./tests/assets/coco_dataset/coco_instances")

def fn(item):
    return True

filtered_dataset = dataset.filter(fn)
print(filtered_dataset)
```

Can I ask you about what version you are using?
Since filtering with a python function is a new feature of 2.0.0 as described https://github.com/openvinotoolkit/datumaro/blob/develop/CHANGELOG.md, please try 2.0.0 :)

**Comment by CourchesneA** [comment]
Oh wow, that's what I was missing. I did not realize that the documentation & code I was looking at did not match my version. I upgraded and now everything is working well. Thanks !
