### ISSUE TITLE
Add split from another dataset

### ISSUE THREAD

**Issue by CourchesneA** [openvinotoolkit/datumaro#1405]
Thanks for the great project and support !

I currently have two datasets in the datumaro format, `my_ds` and `my_test_ds`. What would be the best way for me to merge them such that I have one dataset with two different splits ?

As an extra question, if `my_ds` already have `train` and `val` splits, is there a way for me to add the `test` split from the second dataset ?

**Comment by wonjuleee** [comment]
Hi @CourchesneA, thank you for your steady interests to Datumaro!

Let me start how I reproduced your problem.
Here is the code for creating two datasets with different subset names from Pascal VOC dataset.
```code
from datumaro.components.dataset import Dataset

data_path = "/home/wonju/ssd_ext/datumaro/VOCdevkit/"
dataset = Dataset.import_from(data_path, 'voc')

trainval_dataset = dataset.clone().filter('/item[subset="train" or subset="val"]')
print(trainval_dataset)

test_dataset = dataset.clone().filter('/item[subset="trainval"]')
test_dataset = test_dataset.transform("map_subsets", mapping={"trainval": "test"})
print(test_dataset)
```
This results
![image](https://github.com/openvinotoolkit/datumaro/assets/89109581/989dab0d-2c3c-491b-a058-6b2702abc717)

After that, we can merge them with "union" merge policy as below.
```code
from datumaro.components.hl_ops import HLOps
merged = HLOps.merge(trainval_dataset, test_dataset, merge_policy="union")
print(merged)
```
This makes
![image](https://github.com/openvinotoolkit/datumaro/assets/89109581/e4423917-5f1b-4174-96c1-d5cc71235e3f)

For more complex merge situation such as merging two datasets with different categories, please refer to our notebook for merging heterogeneous datasets here https://github.com/openvinotoolkit/datumaro/blob/develop/notebooks/02_merge_heterogeneous_datasets_for_detection.ipynb.

**Comment by CourchesneA** [comment]
Oh that is much simpler than what I expected, that is awesome. Thanks a lot !
