### ISSUE TITLE
Allow OV >= 2024.0 

### ISSUE THREAD

**Issue by sovrasov** [openvinotoolkit/datumaro#1438]
OTX 2.x will use OV >= 2024.0, so we need to remove the restrictions in https://github.com/openvinotoolkit/datumaro/blob/develop/requirements-core.txt#L37 by OTX 2.1 release

**Comment by wonjuleee** [comment]
I have created the PR for this at https://github.com/openvinotoolkit/datumaro/pull/1450.
If it is required, let me patch this to Datumaro 1.6.1 too.

**Comment by wonjuleee** [comment]
PR https://github.com/openvinotoolkit/datumaro/pull/1450 is merged. Datumaro 1.6.1 will support OpenVINO 2024.0.
