### ISSUE TITLE
build: Library installation fails due to supposedly-missing `crti.o`

### ISSUE THREAD

**Issue by onkoe** [openvinotoolkit/datumaro#1466]
- [failed_compilation.txt](https://github.com/openvinotoolkit/datumaro/files/15052745/failed_compilation.txt): the `rye sync` output with `uv` 
- Linux-Hardware `hw-probe` output: https://linux-hardware.org/?probe=9287fd48fd (includes all packages if you click "Rpms")

Hi there! Unfortunately, I'm not savvy enough with this library to know what's going on, but for some reason, I'm getting an error when attempting to install this library into a clean virtual environment. 

Could you please check the details section and see if anything sticks out to you? The error is related to `ld` being unable to find `crti.o`, though that's installed with the `glibc-devel` package at `/usr/lib64/crti.o`. 

My first thought was to try installing the i686 version of the package (`glibc-devel.i686`) to place the file at `/usr/lib/crti.o`, but this also seemed to have no effect. 

The build only fails with the older version of `pandas`. With `pandas==2.2.2` in my `pyproject.toml`, the build goes perfectly. However, that's too new for `datumaro` and I cannot use the library without the old version (`datumaro==1.6.0 depends on pandas>=1.4.0,<1.5.dev0`). 

Take care,
Barrett

**Comment by vinnamkim** [comment]
Hi @onkoe,
Thanks for your valuable feedback. I made a fix and it will be included in 1.6.1 which will be released soon. If you found any weakness in this project, please don't hesitate to let us know anytime.

**Comment by onkoe** [comment]
Woah, thank you so much for the prompt fix! Excited to get this fantastic library into action. 😄️✨️
