### ISSUE TITLE
LabelMe vs LabelImg confusion in your docs?

### ISSUE THREAD

**Issue by ancri** [openvinotoolkit/datumaro#1488]
Hi, I'm looking through your docs on Supported Data Formats for LabelMe here:

https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/labelme.html

And your examples below use XML files for annotations. AFAIK, LabelMe does not use XML files (it uses JSON files with a different structure) but LabelImg, a totally different platform, does. Is it possible that in your system LabelMe and LabelImg are mixed up?

I've Googled for examples of LabelImg xml files and it indeed matches what you have in your docs for LabelMe e.g.:

https://hammer.purdue.edu/articles/dataset/Annotations/15046332?file=28932813

Best,
Andrei

**Comment by sooahleex** [comment]
Hi @ancri, Thanks for your interest to our project.

We currently support LabelMe data in xml format of [CSAILVision](https://github.com/CSAILVision/LabelMeAnnotationTool?tab=readme-ov-file). This format follows the structure outlined below:
```
.
├── Annotations
│   └── subset1
│       └── img1.xml
├── Images
│   └── subset1
│       └── img1.png
├── Masks
│   └── subset1
│       └── img1_mask_1.png
└── Scribbles
    └── subset1
        └── img1_scribble_1.png
```

We have identified another LabelMe data format used by [labelmeai](https://github.com/labelmeai/labelme?tab=readme-ov-file)
We will evaluate this format and consider adding JSON format support as well. Additionally, we will explore the possibility of supporting the LabelImg format based on compatibility requirements.

Our current LabelMe data format support is limited to XML, adhering to the structure above. We welcome your feedback and suggestions regarding data format support. Let us know if you have any further inquiries or suggestions. We appreciate your continued interest in our project.
