### ISSUE TITLE
Error in boilerplate command for exporting tensorflow with images in docs

### ISSUE THREAD

**Issue by therealpurplemana** [openvinotoolkit/datumaro#1509]
https://openvinotoolkit.github.io/datumaro/latest/docs/get-started/quick-start-guide/examples.html

Page shows this command:

`datum project export --format tf_detection_api -- --save-images`

but the correct command is:

`datum project export --format tf_detection_api -- --save-media`

**Comment by sooahleex** [comment]
Hi @therealpurplemana, Thank you for your interest in our project. We have updated the documentation according to your command. Thank you for bringing this to our attention.
