### ISSUE TITLE
It seems to fail to load uppercase JPEG files from imagenet data set.

### ISSUE THREAD

**Issue by chuneuny-emily** [openvinotoolkit/datumaro#151]
dataset length: 0

![image](https://user-images.githubusercontent.com/55648198/110429812-cfb13100-80ee-11eb-976d-28d92e3fa0c9.png)

**Comment by zhiltsov-max** [comment]
Hi, probably, you're right - it only loads checks for lowercase formats:
https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/imagenet_format.py#L42

Would you like to fix it and contribute a patch?
