### ISSUE TITLE
CLI Format Documentation

### ISSUE THREAD

**Issue by yzb2** [openvinotoolkit/datumaro#1545]
For anyone struggling to use the CLI to export a project into a format, you can see your supported formats with (while in the project folder):
```
datum project info
```
The formats available for `--format` will be there under `Plugins -> extractors`. I could not find this information in the documentation... even resorting to trying to read the code to figure it out. By pure luck and desperation, I tried this command and it's there.

To reproduce this, be a beginner trying a basic workflow: 
- Oh, it [supports YOLO-Ultralytics](https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/index.html) exporting, let me try that as the format. 
- Oh, the format name is invalid.
- Well... Is there anywhere that shows the format arguments for the CLI, or somewhere that points me to them?
- Spend a long time trying to find it, or give up on the tool entirely.

This should be easy information to find (and if it is, boy am I blind).

That being said, thank you for this amazing tool.

**Comment by vinnamkim** [comment]
Hi @1dmesh,
Thank you for your valuable interest in our project. Your feedback on the user experience is truly appreciated. It helps us identify areas for improvement and enhances our project overall. I'll create a ticket to enhance our documentation and CLI as you suggested.

**Comment by vinnamkim** [comment]
Added a new CLI command for this use case, https://github.com/openvinotoolkit/datumaro/pull/1570
