### ISSUE TITLE
Issue in combining two COCO json file

### ISSUE THREAD

**Issue by smandhada16** [openvinotoolkit/datumaro#16]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

I annotated two sets of images separately in CVAT and then want to combine those annotation files.
When I tried to combine two COCO JSON file annotated in CVAT, the annotations are not loading for the images.

### Expected Behaviour

When I load two separate annotation files then the annotation should be loaded for the images

### Current Behaviour
 
Only few annotations are loading

### Steps to Reproduce (for bugs)

1. Annotate two images separately and export the COCO annotation files separately.
2.Load the two images into a single job and import the two COCO annotation files.
3.Now, we can see that the annotations are not loaded.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by smandhada16** [comment]
@nmanovic Do you mean the above mentioned functionality will be implemented in your next projects.

**Comment by nmanovic** [comment]
@smandhada16 , I mean that we will implement a special feature in CVAT which should cover the case. But Datumaro should support the feature already now.

**Comment by zhiltsov-max** [comment]
@smandhada16, please try with an updated version of Datumaro:

```bash
pip install 'git+https://github.com/openvinotoolkit/datumaro@zm/coco-reindexing' # @zm/coco-reindexing until PR merged
datum project import -f coco -i /src1 -o src1_proj
datum project import -f coco -i /src2 -o src2_proj
datum merge src1_proj src2_proj
datum project export -p merged -f coco -- --reindex
```

**Comment by smandhada16** [comment]
The above solution also didn't work and still the labels are missing

**Comment by zhiltsov-max** [comment]
What is missing specifically?

**Comment by smandhada16** [comment]
When I combine two separate annotation file and then imported the integrated then the labels are not loaded for the images

**Comment by zhiltsov-max** [comment]
Could you share the annotation files?

**Comment by smandhada16** [comment]
[task_t1-2020_09_09_16_35_46-coco 1.0.zip](https://github.com/openvinotoolkit/datumaro/files/5272834/task_t1-2020_09_09_16_35_46-coco.1.0.zip)
[task_t2-2020_09_09_16_40_27-coco 1.0.zip](https://github.com/openvinotoolkit/datumaro/files/5272836/task_t2-2020_09_09_16_40_27-coco.1.0.zip)
These two files I want to integrate and generate a single JSON file. After that I want to import the integrated file

**Comment by zhiltsov-max** [comment]
Using the commands above, I was able to join and import the annotations. However, the annotations you shared have the problem fixed in #10, so you need to reexport them using a newer version of CVAT or reexport in another format (e.g. "CVAT for images"), or fix annotation ids manually.

**Comment by Tbeck-91** [comment]
>'''
> datum project create -o merged
> cd merged
> datum source add path -n src1 -f coco_instances /dir1/instances_default.json
> datum source add path -n src2 -f coco_instances /dir2/instances_default.json
> datum project export -f coco_instances
> ```

this doesn't update the image ids! I followed this and ended up with an annotations filed where all my images had duplicate  ids!

**Comment by zhiltsov-max** [comment]
@Tbeck-91, try the solution described here: https://github.com/openvinotoolkit/datumaro/issues/112#issuecomment-783645671. If the annotation files have the same image ids (but images aren't the same), you'll need to rename them. It can be done with `reindex` ([docs](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/transforms.py#L261)) or `rename` ([docs](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/transforms.py#L401)) transforms. They can be used like this ([docs](https://github.com/openvinotoolkit/datumaro/blob/develop/docs/user_manual.md#transform-project)): 

```
# rename the first annotations
datum import -f coco_instances -i /dir1/instances_default.json -o proj1
datum transform -t rename -p proj1 -o proj1_renamed -- -e "|(.*)|task1_\\1|"

# rename the second annotations
datum import -f coco_instances -i /dir2/instances_default.json -o proj2
datum transform -t rename -p proj2 -o proj2_renamed -- -e "|(.*)|task1_\\1|"

datum create -o merged
cd merged
datum source add path -n src1 -f datumaro /proj1_renamed/dataset
datum source add path -n src2 -f datumaro /proj2_renamed/dataset
datum export -f coco_instances [-- --save-images --reindex]
```

**Comment by MiguelAngeloMartinsRibeiro** [comment]
Hi @zhiltsov-max I used you first solution in order two merge two coco .json files that I got from labelme. Each one of them have the annotations of 5000 images with different filenames but the ids on both is from 1 to 5000.

pip install 'git+https://github.com/openvinotoolkit/datumaro'
datum project create -o merged
cd merged
datum source add path -n src1 -f coco_instances /dir1/instances_default.json
datum source add path -n src2 -f coco_instances /dir2/instances_default.json
datum project export -f coco_instances

So the result was bad. We just considered 5000 images and merged the annotations on those 5000 images.
What I basically want is to merge two datasets with different images and different annotations in on .json file in order to train my network.

I saw your reindex comments but I couldn't figure it out cause you use proj1 and proj2 and I don't have projects also your #112(comment) is about tasks and I don't have tasks too

If you could help me out I would really appreciate it

**Comment by zhiltsov-max** [comment]
@MiguelAngeloMartinsRibeiro, it looks like my previous comment fits your case, or maybe I'm missing something?

It looks like any of `reindex`, `rename` and `id_from_image_name` (if image names are all different, [docs](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/transforms.py#L391)) transforms will be helpful in your case.

> I saw your reindex comments but I couldn't figure it out cause you use proj1 and proj2 and I don't have projects also your #112(comment) is about tasks and I don't have tasks too

The approach I propose is the following: 
- the initial annotation files are imported to new datumaro projects
- these projects are transformed
- the resulting annotations (now in the datumaro format) are added into another new datumaro project and merged there, then exported

Please try these commands (I re-checked the past answers and adjusted the commands a bit):

```bash
# rename the first annotations (store them in a new datumaro project)
datum create -o proj1/
datum add path -p proj1/ -f coco_instances /dir1/instances_default.json
datum transform -t id_from_image_name -p proj1/ -o proj1_renamed/

# rename the second annotations (store them in a new datumaro project)
datum create -o proj2/
datum add path -p proj2/ -f coco_instances /dir2/instances_default.json
datum transform -t id_from_image_name -p proj2/ -o proj2_renamed/

datum create -o merged/
datum add path -n src1 -f datumaro proj1_renamed/dataset/ -p merged/
datum add path -n src2 -f datumaro proj2_renamed/dataset/ -p merged/
datum export -f coco_instances -p merged -- --reindex # + optionally add  --save-images
```

**Comment by antoniofurioso** [comment]
Hey Guys, I have a question. Can I use this method to join the coco annotation file with lvis annotation file? They have the same dataset. How can I join these two files?

**Comment by zhiltsov-max** [comment]
Looking at https://www.lvisdataset.org/dataset, I can say that the format is different, though it is similar to COCO. This format is not supported in Datumaro yet, so you'll need to write some code. If you need to import such annotations you'll need an `Extractor` plugin like [this](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/coco_format/extractor.py#L25-L154) and for exporting you'll need a `Converter` plugin like [this](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/coco_format/converter.py#L514-L670). More information about plugins is available in our docs [here](https://openvinotoolkit.github.io/datumaro/docs/developer_manual/#plugins). A simple example of a format plugin is [here](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/imagenet_format.py) Basically, you need to create a `.py` file and put it to `project/.datumaro/plugins/`, along with an empty `__init__.py` file. We are open for pull request with new formats, so if you have an opportunity to contribute, you're welcome.

**Comment by vigi30** [comment]
@zhiltsov-max  I am trying to merge two coco annotation files that I got from cvat using this [comment](https://github.com/openvinotoolkit/datumaro/issues/16#issuecomment-893260740). However, I am getting the below error 

`datum add: error: the following arguments are required: -f/--format`  for the following command 

`datum add path -p proj1/ -f coco_instances /home/vigneshs/data/v0_clean/test/annotations/test_annotations.json`

I have two annotations files-- `test_annotations.json` and `v1_test_annotations.json` which I want to combine. Adding the first annotation path itself throwed the error.
`/home/vigneshs/data/v0_clean/test/annotations/test_annotations.json` is the path to my first annotation file.

Could you please help me out in resolving this issue?

**Comment by zhiltsov-max** [comment]
@vigi30, hi. The comment you're referring to is a bit outdated. In newer versions of Datumaro (v0.3) the `add` command was changed, and the `"path"` part is no longer needed. You can find docs [here](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/sources/). In your case, the command should look like this:

`datum add -p proj1/ -f coco_instances /home/vigneshs/data/v0_clean/test/annotations/test_annotations.json`
\- if you want to work with just a separate annotation file

or

`datum add -p proj1/ -f coco_instances -r annotations/test_annotations.json /home/vigneshs/data/v0_clean/test/`
\- if you want to work with a specific annotation file in a [COCO-like dataset](https://github.com/openvinotoolkit/datumaro/tree/develop/tests/assets/coco_dataset/coco_instances) directory.

Also, take a look at the [`patch` command](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/patch/), which can be useful to join 2 datasets in simple cases. The command will look like this:
`datum patch -o merged/ test_annotations.json:coco_instances v1_test_annotations.json:coco_instances` 
(maybe with `--reindex 1` option, if you want new image/annotation indices in the output dataset, [docs](https://openvinotoolkit.github.io/datumaro/docs/formats/coco/#export-to-coco)).

**Comment by harishbp** [comment]
import json

def merge_coco_datasets(file1, file2, output_file):
    with open(file1, 'r') as f1:
        coco1 = json.load(f1)
    with open(file2, 'r') as f2:
        coco2 = json.load(f2)

    # Adjust image IDs and annotation IDs
    max_image_id = max(coco1['images'], key=lambda x: x['id'])['id']
    for image in coco2['images']:
        image['id'] += max_image_id
    max_annotation_id = max(coco1['annotations'], key=lambda x: x['id'])['id']
    for annotation in coco2['annotations']:
        annotation['id'] += max_annotation_id
        annotation['image_id'] += max_image_id

    # Merge image and annotation data
    coco1['images'].extend(coco2['images'])
    coco1['annotations'].extend(coco2['annotations'])

    # Update category IDs if necessary

    # Save the merged JSON file
    with open(output_file, 'w') as outfile:
        json.dump(coco1, outfile)
        print("Merged COCO JSON file saved as", output_file)

# Example usage

merge_coco_datasets('coco1.json', 'coco2.json', 'merged_coco.json')

**Comment by harishbp** [comment]
#start

import json

def merge_coco_datasets(file1, file2, output_file):
    with open(file1, 'r') as f1:
        coco1 = json.load(f1)
    with open(file2, 'r') as f2:
        coco2 = json.load(f2)

    # Adjust image IDs and annotation IDs
    max_image_id = max(coco1['images'], key=lambda x: x['id'])['id']
    for image in coco2['images']:
        image['id'] += max_image_id
    max_annotation_id = max(coco1['annotations'], key=lambda x: x['id'])['id']
    for annotation in coco2['annotations']:
        annotation['id'] += max_annotation_id
        annotation['image_id'] += max_image_id

    # Merge image and annotation data
    coco1['images'].extend(coco2['images'])
    coco1['annotations'].extend(coco2['annotations'])

    # Update category IDs if necessary

    # Save the merged JSON file
    with open(output_file, 'w') as outfile:
        json.dump(coco1, outfile)
        print("Merged COCO JSON file saved as", output_file)

# Example usage

merge_coco_datasets('coco1.json', 'coco2.json', 'merged_coco.json')
#end

#copy from start to end

**Comment by muradaghyv** [comment]
> #start
> 
> import json
> 
> def merge_coco_datasets(file1, file2, output_file): with open(file1, 'r') as f1: coco1 = json.load(f1) with open(file2, 'r') as f2: coco2 = json.load(f2)
> 
> ```
> # Adjust image IDs and annotation IDs
> max_image_id = max(coco1['images'], key=lambda x: x['id'])['id']
> for image in coco2['images']:
>     image['id'] += max_image_id
> max_annotation_id = max(coco1['annotations'], key=lambda x: x['id'])['id']
> for annotation in coco2['annotations']:
>     annotation['id'] += max_annotation_id
>     annotation['image_id'] += max_image_id
> 
> # Merge image and annotation data
> coco1['images'].extend(coco2['images'])
> coco1['annotations'].extend(coco2['annotations'])
> 
> # Update category IDs if necessary
> 
> # Save the merged JSON file
> with open(output_file, 'w') as outfile:
>     json.dump(coco1, outfile)
>     print("Merged COCO JSON file saved as", output_file)
> ```
> 
> # Example usage
> merge_coco_datasets('coco1.json', 'coco2.json', 'merged_coco.json') #end
> 
> #copy from start to end

Thank you so much !
