### ISSUE TITLE
Filter does not work in project created using 'import'

### ISSUE THREAD

**Issue by Once88** [openvinotoolkit/datumaro#161]
I created a project using the `import` command. Then I run `datum filter -p xxx -m i+a -e 'item/annotation[label="person"]'`, the image and annotation folder are all empty.

**Comment by zhiltsov-max** [comment]
Hi, you can check what you're trying to filter and what is going to be saved with:

```bash
datum filter -p xxx -m i+a --dry-run # check what is filtered
datum filter -p xxx -m i+a -e 'item/annotation[label="person"]' --dry-run # check filtering results
```

The results are saved in another directory, which name is printed in the console after successful completion. If you want to export in the original format, use `datum export -p xxx-filter ... [-- --save-images]` or you can even join `export` and `filter` and use only `datum export -p xxx --filter-mode i+a -e ...`

**Comment by Once88** [comment]
Thanks. It worked after I did the following two things:
1. install `tensorflow` and update `numpy`.
2. add a slash before the value of `-e`, like this `-e '/item/annotation[label="person"]'`.
