### ISSUE TITLE
Support arbitrary image extensions in formats

### ISSUE THREAD

**Issue by zhiltsov-max** [openvinotoolkit/datumaro#166]
Most of formats do not specify the image format they use. Some do, but it is very useful for the framework to support arbitrary image extensions to avoid useless reconverting between formats on exporting and to relax requirements on importing datasets.

Formats:
  - [ ] COCO
  - [ ] PASCAL VOC
  - [ ] YOLO
  - [ ] TF Detection API
  - [ ] WIDER Face
  - [ ] VGGFace2
  - [ ] MOT sequences
  - [ ] MOTS PNG
  - [ ] ImageNet
  - [ ] CamVid
  - [ ] CVAT
  - [ ] LabelMe
  - [ ] ICDAR13/15
  - [ ] Market-1501
  - [ ] LFW

**Comment by mrd** [comment]
I found that PNG files were still hardwired into the CVAT converter. To fix this I used `glob.glob`. Before I submit a pull request can I make sure that `import glob` is acceptable in the cvat plugin, or would you rather it be done another way?

changes: https://github.com/openvinotoolkit/datumaro/compare/develop...AdaptiveCity:arbitrary-image-format-cvat-converter

**Comment by zhiltsov-max** [comment]
@mrd, good observation. I'm not convinced it is reasonable to use lossy formats for video frames, but it definitely should be allowed. Globbing is allowed, but I'd suggest to change your implementation to use [the approach from other formats](https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/voc_format/extractor.py#L86-L97) to avoid repeated OS calls.
