### ISSUE TITLE
Request for Comprehensive Statistics Command Covering All Annotation Types

### ISSUE THREAD

**Issue by ainayves** [openvinotoolkit/datumaro#1661]
Hello , Is there a command or a function  that provides statistics for all annotation types, such as bounding boxes, polygons, keypoints, etc.? Using the Detection Validator only gives us stats for bounding boxes, and for segmentation, it only provides stats for polygons.
Thank you in advance !!

**Comment by reticia** [comment]
Hi @ainayves, I'm sorry for the late response.
Yes, there's a statistics function, `compute_ann_statistics`. You can get the stats by annotation types. Please refer [this link](https://github.com/openvinotoolkit/datumaro/blob/028f9f759ae4cf0ce31f22b1790f5c8a1f4e3683/src/datumaro/components/operations.py#L255). 
If you wan to use CLI, please check `datum stats --help`.
I hope this will help you.

**Comment by jihyeonyi** [comment]
Hi @ainayves, I'm sorry for the late response.
Yes, there's a statistics function, `compute_ann_statistics`. You can get the stats by annotation types. Please refer [this link](https://github.com/openvinotoolkit/datumaro/blob/028f9f759ae4cf0ce31f22b1790f5c8a1f4e3683/src/datumaro/components/operations.py#L255).
If you wan to use CLI, please check `datum stats --help`.
I hope this will help you.

**Comment by ainayves** [comment]
Hello @jihyeonyi , thank you very much , it was very helpful
