### ISSUE TITLE
Dump Anotations: LabelMe3.0 supports only Flat Image Layout

### ISSUE THREAD

**Issue by veer5551** [openvinotoolkit/datumaro#17]
### My actions before raising this issue
- [  ] Searched [past issues] - https://github.com/openvinotoolkit/cvat/pull/1715/files

### Expected Behaviour
Dumping Annotations in LabelMe3.0 Format. Annotations should be dumped with File (Image) name and should remove the base path (head of the file name). 
Eg. root/Folder_containing_images/Image1.jpg -- > Annotations in LabelMe3.0 should be dumped as Image1.xml

### Current Behaviour
Currently, I am uploading the image data from the shared drive on the CVAT tool. Hence the Images are uploaded with base path + filename (root/Folder_containing_images/Image1.jpg). While Dumping Annotations in LabelMe3.0, it raises an error as it is only expecting a flat layout for the Image name

### Possible Solution
Support Relative Path/ Absolute Path for LabelMe3.0.
Reference - https://github.com/openvinotoolkit/cvat/pull/1715/files

### Steps to Reproduce (for bugs)

1. Upload the Image Data from Shared Drive.
1. Dump annotations in LabelMe3.0 format

### Context
I am trying to Upload the Annotations file to verify and correct the Labels. LabelMe3.0 suits for the application as it generates an individual XML file for each image and supports polygon labels and attributes as well. Converters are designed to/from LabelMe3.0 to a custom format. It will be great if it is possible to support the relative/absolute path (without flat layout) in the LabelMe3.0 format as well.

Also, Open for suggestions if any other Annotations formats can be suitable (generates a separate file and supports polygon and attributes) and used.

Thanks a lot!

### Your Environment

CVAT tool is deployed on AWS instance

**Comment by zhiltsov-max** [comment]
The problem is how to save it (so we could adequately parse it), if the format looks like this: https://github.com/openvinotoolkit/datumaro/tree/develop/tests/assets/labelme_dataset

I see the only solution in truncating paths to names (without extensions) and check for collisions.

**Comment by veer5551** [comment]
Hello @zhiltsov-max and @nmanovic,

Thanks for the Support!
I encountered the following issue with LabelMe3.0 format with latest CVAT version (cloned just few hours back)

1. While Uploading the Annotations, it gives the following error:
**Steps to Reproduce**
a. Upgrade to latest CVAT
b. Upload Data 
c. Upload respective Annotations
 (currently I have tried just absolute path Image Data and Label Data)
Labels are converted to LabelMe3.0 XML format are working fine with Previous versions of CVAT.
```
Could not upload annotation for the task 3
Error: Request failed with status code 500. "AttributeError: 'NoneType' object has no attribute 'text'\n".
```


2. While dumping the Annotations, All the labels are renamed to `item_00000xxxx.xml` instead of the Frame ID.
**Steps to Reproduce:**
a. Upgrade to latest CVAT
b. Upload data 
c. Annotate and Dump in LabelMe3.0 format

Could you have a look and Help!


Older version of CVAT wouldn't remain for a longer time with me!
Thanks a lot!

**Comment by zhiltsov-max** [comment]
Hi, 

1. could you post the whole error message with the stack trace?
2. I could not find a better solution. There is a `folder` field in XMLs, which contains the path, an `name` with the name. I you have better ideas, we can discuss them.

**Comment by veer5551** [comment]
Hello,
1. Could you please guide me for collecting Error with stack trace.
2. Is it possible to create sub-directories same as that of the share-file path?
Eg. lets say I have Share-file Path: 
`/root/ImageData/Folder1,Folder2.,Folder3`... so on
And **Task_xx** contains only `/root/ImageData/Folder1` and `/root/ImageData/Folder2`.

So while dumping the Annotations, 
1. Create sub-directories recursively --> Eg. from `root/ImageData.Folder1`... and so on .. OR
2. Or just Take the **pen-ultimate** directory --> here as` Folder1/Folder2  
`( create them inside or outside the current **default** directory) and store the respective Folders Annotations in them.

Let me know if its possible and your thoughts on it!

Thanks a lot for the support!

**Comment by zhiltsov-max** [comment]
To obtain a stack trace, run `docker logs cvat` after an error.

Using
```
Masks/a/b/c_1.png
          /a/b/c_2.png
          /a/d/c_1.png
          /a/d/c_2.png
a/b/c.xml
a/d/c.xml
```
is an option. It is questionable, if it is really labelme format, though.

**Comment by veer5551** [comment]
Thanks @zhiltsov-max,

 Do we support relative paths or other Annotations Format, with same layout as their Image (like you mentioned)?

> Masks/a/b/c_1.png
> Masks/a/b/c_2.png
> Masks/a/d/c_1.png
> Masks/a/d/c_2.png
> a/b/c.xml
> a/d/c.xml

And How Labelme is different from them, as its not suitable for these type of Dumping?

Thanks!

**Comment by veer5551** [comment]
Hello again Team,

Thanks a lot for the Support on the Issue!
Need a small quick Help again.

I was trying to Upload the Annotations with with Same directory structure and got the below error.
![image](https://user-images.githubusercontent.com/41330355/101595823-086f3a80-3a1a-11eb-8819-a4a12e1ed5d3.png)

Is it the right way of uploading the Annotations i.e with the same structure as that of File-Share.

Thanks a lot!

**Comment by zhiltsov-max** [comment]
Hi,

What do you mean by "same directory structure"?

Please check if the uploaded archive has an extra directory in the root.

**Comment by veer5551** [comment]
Same Directory Structure means:
Lets say I have File-share path as: `root/Image_Data/Folder1, Folder2 ...`
How Do I upload the Annotations for this Task?

Did the following things
1. Can upload only a single Tasks Annotation folder. If tried to Upload Multiple Folders inside a single Zip, raises Error.
Structure of Annotations: `Annotations/Folder1, Folder2 ...` (Each FOlder having Annotations in xml)
2. Also tried to collect all the Tasks Annotations in same folder and Upload it. Raises Error for not finding any matching Frame.
Structure of Annotations: `Annotations/folder1_image__xxx.xml, folder2_image_xxx.xml ...`

Thanks!

**Comment by zhiltsov-max** [comment]
In general, you can always check the expected structure by drawing some annotations in the task and dumping. All the formats should be able to dump and upload then.

I think, the problem is that the expected format is like in 2, but `<filename>` and `<folder>` tags in annotations should be filled with the right values.

**Comment by veer5551** [comment]
Thanks for the Help!
Works Perfectly!

Usage - 
1. Collect the required Folders XMLs in one folder.
Make sure you fill the `<filename>` and `<folder>` tags with appropriate values (same as that of your Shared Path)
2. Zip it up and Upload.

Thanks a lot!
