### ISSUE TITLE
create subset folders when converting voc to coco /w save-images option

### ISSUE THREAD

**Issue by jihyeonyi** [openvinotoolkit/datumaro#183]
When I convert the voc-format data to coco format with the `--save-images` option, I've expected that output images are under their subsets, but I couldn't find subsets.

In the [user manual - Import project](https://github.com/openvinotoolkit/datumaro/blob/develop/docs/user_manual.md#import-project), I can find COCO-like format as below.
```
COCO/
├── annotations/
│   ├── instances_val2017.json
│   ├── instances_train2017.json
├── images/
│   ├── val2017
│   ├── train2017
```

But after converting the dataset to coco format, I've got the format below.
```
COCO/
├── annotations/
│   ├── instances_val2017.json
│   ├── instances_train2017.json
├── images/
```
All the images are under the `images` folder, not under the `images/val2017` or `images/train2017` folder.
I think it should be the same as the first example.

In addition, the 2nd format is also described in the [user manual - Add and remove data](https://github.com/openvinotoolkit/datumaro/blob/develop/docs/user_manual.md#add-and-remove-data).
I think we need to update the user manual, too.

**Comment by zhiltsov-max** [comment]
Currently, import supports both variants, but export only produces a single `image/` folder. It matches the file layout in the original dataset. Do you think we need to provide an option to split images into subdirectories?

**Comment by jihyeonyi** [comment]
I'm not sure actually.
I've tried to convert the voc data to coco style to train some [OTE models](https://github.com/openvinotoolkit/training_extensions/tree/develop/models/object_detection).
If the OTE training code supports a single `image/` folder, I think the current export scheme is acceptable. 
Let me check the training code first.

**Comment by jihyeonyi** [comment]
I didn't train OTE models with a single `image/` folder, but I found that OTE instance segmentation uses the folder structure below.
```
data
├── coco
    ├── annotations
    ├── train2017
    ├── val2017
    ├── test2017
```
So, in my opinion, it'd be useful if we provide an option to split images into subdirectories, even though we can do the same thing by filtering.
How do you think?

**Comment by zhiltsov-max** [comment]
Ok, it should not be hard to do. This option will be disabled by default.
