### ISSUE TITLE
dataset.export not working as expected

### ISSUE THREAD

**Issue by anwar1997ff** [openvinotoolkit/datumaro#193]
When i try to import a dataset and export it again, only the label files are created, not the images. (the images are read correctly by dataset import)
`dataset = Dataset.import_from("path/to/dataset", 'yolo')`
`dataset.export('output_path', 'yolo')`

I saw that in the equivalent cli command there is an extra argument to save the images, however i could not find in the docs an equivalent for the python function call.

am i missing something ?
thanks for your support

**Comment by zhiltsov-max** [comment]
Hi, in the API pass `dataset.export(..., save_images=True)`.

**Comment by anwar1997ff** [comment]
Thank you
