### ISSUE TITLE
Warning when trying to export yolo dataset after split

### ISSUE THREAD

**Issue by anwar1997ff** [openvinotoolkit/datumaro#194]
Steps to reproduce:
`dataset = Dataset.import_from("/path/to/dataset", 'yolo')`
`dataset.transform('detection_split', [('train', 0.5),('val', 0.5)])`
`dataset.export('/output/path', 'yolo')`

Warning:
`WARNING:root:Skipping subset export 'val'. If specified, the only valid names are 'train', 'valid'`

Which wont save the val data in the dataset.

Replacing "valid" with "val" in datumaro/datumaro/plugins/yolo_format/format.py solved this issue, but not sure if it raises other conflicts

**Comment by zhiltsov-max** [comment]
Hi. If a subset name is different from `train` and `valid` (https://github.com/AlexeyAB/darknet/blob/master/src/detector.c#L30), the training framework will fail to use it. But you're right, splitters need to support different subset names.

**Comment by jihyeonyi** [comment]
Currently, we're restricting the subset name in the detection_split, but it's possible to support different subset names. 
This is the same for the classification_split.
So, I'll change them for both splitting algorithms.
