### ISSUE TITLE
Export fails when some annotation files are empty

### ISSUE THREAD

**Issue by anwar1997ff** [openvinotoolkit/datumaro#202]
When trying to export a dataset with the following call:
`dataset_out.export(output_path, format, save_images=True)`
The following error occurs:
`~/.local/lib/python3.8/site-packages/datumaro/plugins/splitter.py in _group_by_bbox_labels(dataset)
    486             bbox_anns = [a for a in item.annotations
    487                 if a.type == AnnotationType.bbox]
--> 488             assert 0 < len(bbox_anns), \
    489                 "Expected more than one bbox annotation in the dataset"
    490             for ann in bbox_anns:

AssertionError: Expected more than one bbox annotation in the dataset`

This causes an issue since sometimes it is important to keep images without annotation as part of the dataset (negtive samples)

**Comment by jihyeonyi** [comment]
Could you give me the full sequence?

**Comment by jihyeonyi** [comment]
Should images without annotations be split into train/val/test?
Or, can I make it a separate subset such as 'unlabeled'?

**Comment by anwar1997ff** [comment]
they should be split into train/val/test in my opinion. This way the dataset is ready for training/testing. And if a user wants to retrieve the unlabeled images for some reason it can be easily done with (dataset.select(lambda item: len(item.annotations) == 0)

**Comment by jihyeonyi** [comment]
Thank you for your opinion. 
This module was originally designed for annotated data only, but I'll split unannotated data into specified subsets, too.
This will be applied to all task-specific splitters.
