### ISSUE TITLE
Support multiple image extensions with CVAT

### ISSUE THREAD

**Issue by MathieuHaller** [openvinotoolkit/datumaro#213]
Hello,

Currently, when using the datumaro API in python:  
`dataset.export(..., format="cvat", save_images=True, image_ext=".png")`  
will **always** output images in .jpg format.  

That is due to line 167 in datumaro/plugins/cvat_format/converter.py :  
`filename = item.id + CvatPath.IMAGE_EXT`  
CvatPath.IMAGE_EXT is ".jpg".    
Changing this line with:   
`filename = item.id + self._context._image_ext`  
fixes the issue and makes it possible to use any desired image extension while exporting a dataset.  

To be honest:  
- I do not know if this falls under bug fixing or a new feature entirely, as the current behavior might be the desired one.  
- I don't have much experience with open source projects. If my issue seems ok, should I open a merge request fixing it ?

**Comment by zhiltsov-max** [comment]
Hi, it was changed in https://github.com/openvinotoolkit/datumaro/issues/166, which is a part of v0.1.7. The change allows to keep the original image extension on export (unless required a specific one) and look for images with different extensions during import (when not specified by dataset format). Try to update with `pip install datumaro --upgrade` and check.

**Comment by zhiltsov-max** [comment]
@MathieuHaller, please check if the patch helps. To check do `pip install git+https://github.com/openvinotoolkit/datumaro@zm/fix-image-ext-in-cvat`.

**Comment by MathieuHaller** [comment]
@zhiltsov-max The patch does seem to fix the issue on my end, specifying image_ext is now taken into account for CVAT export.  
Thanks for the quick reaction !
