### ISSUE TITLE
supporting to manipulate attribute.

### ISSUE THREAD

**Issue by chuneuny-emily** [openvinotoolkit/datumaro#218]
user can remove a specific attribute itself, rather than filter it by conditional on a specific attribute value.

Use case:
All images are have age(kids, adult, old), gender(male, female) and hat(yes, no) attribute. 
I’d like to remove gender attribute itself in 'A' dataset, and to remove age attribute itself in 'B' dataset.

**Comment by zhiltsov-max** [comment]
Also consider removal attributes in any label and in a specific label. An attribute can be "common" (applied to all labels, stored in `categories.attributes`), so it might need to copy these attributes into all the labels or maybe reject the idea of common labels.
