### ISSUE TITLE
Return format is not uniform

### ISSUE THREAD

**Issue by Ryanshuai** [openvinotoolkit/datumaro#219]
https://github.com/openvinotoolkit/datumaro/blob/b3eaf4a5035ad37c4cf591643b5d0f4b18f64992/datumaro/util/annotation_util.py#L182

is different from 

https://github.com/openvinotoolkit/datumaro/blob/b3eaf4a5035ad37c4cf591643b5d0f4b18f64992/datumaro/util/annotation_util.py#L213

**Comment by zhiltsov-max** [comment]
Thanks, you're right.
