### ISSUE TITLE
Readable COCO and datumaro format for CJK

### ISSUE THREAD

**Issue by jaesuny** [openvinotoolkit/datumaro#231]
When a dataset with categories in CJK (e.g., "고양이", "ネコ", "猫") is converted to COCO or datumaro and writed, the categories are saved in Unicode as below.
```json
"categories": [{
    "id": 1,
    "name": "\uace0\uc591\uc774",
    "supercategory": ""
}, {
    "id": 2,
    "name": "\u30cd\u30b3",
    "supercategory": ""
}, {
    "id": 3,
    "name": "\u732b",
    "supercategory": ""
}],
```
There is no problem when loading this file, but I feel inconvenient when reading the json file directly.

I think this would be done by adding `ensuer_ascii = False` to `json.dump` in https://github.com/openvinotoolkit/datumaro/blob/ec4b013308534681d23ae3720dde7cdb844aed21/datumaro/plugins/coco_format/converter.py#L98-L99 and https://github.com/openvinotoolkit/datumaro/blob/ec4b013308534681d23ae3720dde7cdb844aed21/datumaro/plugins/datumaro_format/converter.py#L103-L104

Thank you.

**Comment by zhiltsov-max** [comment]
Hi. I see no problems in using Unicode characters in JSON, because it is supported by the standard. Do you think it should be an option or a default behaviour? Also, you're welcome to create a PR and contribute.

**Comment by Jaesuny** [comment]
> Hi. I see no problems in using Unicode characters in JSON, because it is supported by the standard. Do you think it should be an option or a default behaviour? Also, you're welcome to create a PR and contribute.

Yes. It's just because of the inconvenience.
I think it could be a default behaviour.
I'll create a PR.

Thanks.
