### ISSUE TITLE
AttributeError: '_DatasetFilter' object has no attribute 'export'

### ISSUE THREAD

**Issue by Arthur151** [openvinotoolkit/datumaro#247]
While I try to filter out an image from the whole coco keypoint dataset, an error occured:
```
datum export --filter '/image[COCO_train2014_000000005638.jpg]' --format cvat --output-dir COCO_train2014_000000005638
or
datum export --filter '/COCO_train2014_000000005638.jpg' --format cvat --output-dir COCO_train2014_000000005638
```

```
2021-05-19 20:48:11,137 INFO: Loading the project...
creating index...
index created!
creating index...
index created!
2021-05-19 20:53:30,174 INFO: Exporting the project...
2021-05-19 20:53:30,174 ERROR: '_DatasetFilter' object has no attribute 'export'
Traceback (most recent call last):
  File "/home/yusun/anaconda3/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/home/yusun/anaconda3/lib/python3.7/site-packages/datumaro/cli/__main__.py", line 123, in main
    return args.command(args)
  File "/home/yusun/anaconda3/lib/python3.7/site-packages/datumaro/cli/contexts/project/__init__.py", line 348, in export_command
    dataset.export(format=args.format, save_dir=dst_dir, **extra_args)
AttributeError: '_DatasetFilter' object has no attribute 'export'
```

**Comment by zhiltsov-max** [comment]
Hi, it was fixed in #209, but we haven't released this yet. Could you try to use the current develop version?

`pip install --force-reinstall 'git+https://github.com/openvinotoolkit/datumaro@develop' `

**Comment by Arthur151** [comment]
It turns out that this develop version is extremely hard to install...

**Comment by zhiltsov-max** [comment]
Could you provide more information? What was hard, what works slow, how to reproduce?

**Comment by zhiltsov-max** [comment]
> [...] will force to re-install all related libraries, which caused a lot of conflicts.

Probably, `--no-deps` flag could help in this case.


Could you describe the project's contents? Looking at the commands, I can guess there is a COCO dataset, from which you are trying to extract keypoint annotations and put all of them into separate files in CVAT format. Currently, Datumaro CLI is more about batch operations on datasets, so if you need to filter and export all the images as separate datasets, some simple code might be needed to make it faster.

You can check item XML representations to be filtered and the potential output of the filter with `datum filter ... --dry-run`. The filter expression above looks incorrect, probably you wanted to use `-e '/item[id="COCO_train2014_000000005638"]'`.

How many sources in the project? If there are few sources, they needs to be merged first, we can speed up the process in the case.

**Comment by Arthur151** [comment]
Hi, thanks a lot for your kind instruction.
COCO keypoint dataset (https://cocodataset.org/#keypoints-2020) is a 2D datasets with 2D pose annotations.
We want to load all images along with their available 2D keypoint annotations into the cvat for annotating other attribute of each person (such as gender). 
I am stuck at importing COCO keypoint dataset into cvat for adding other annotations.

**Comment by Arthur151** [comment]
Thanks for your time and effort!
