### ISSUE TITLE
Merging of datasets

### ISSUE THREAD

**Issue by fgabel** [openvinotoolkit/datumaro#256]
Hi!

Using the Python API, how can I merge two datasets with a common id (name of images is identical, but annotations types are different)?

When I do, I get a  `datumaro.components.errors.DatumaroError: Merging of datasets with different categories is only allowed in 'merge' command.`
There does not seem to be a merge command for Python?

**Comment by zhiltsov-max** [comment]
Hi, look at `datumaro.components.IntersectMerge` class. Examples of use are here: https://github.com/openvinotoolkit/datumaro/blob/develop/tests/test_ops.py#L217

**Comment by fgabel** [comment]
Hello Maxim,

This worked, but it's painfully slow (~12hrs) for my dataset of ~7k items, it seems to be squared complexity. As I only have to run this once, it's fine, but are there any simpler methods to achieve this? The labels I am trying to merge are mutually exclusive, so should be much faster.

**Comment by zhiltsov-max** [comment]
Hi. This function really has high computational complexity, but it can be optimized. There is the second way of merging I mentioned, which is simple and has linear complexity. But it may require some changes to the datasets merged. As I said, it will require datasets to have same label sets and it is supposed to be used in simple situations, when annotations are either completely equal or completely not equal (no partial overlaps). To align label sets and merge, you can either change dataset manually or use the following snippet:

```python
from datumaro.components.dataset import Dataset
from datumaro.components.extractor import AnnotationType

dataset1 = Dataset.import_from(path1, format)
labels1 = dataset1.categories()[AnnotationType.label]

dataset2 = Dataset.import_from(path2, format)
labels2 = dataset2.categories()[AnnotationType.label]
for label1 in labels1:
    labels2.add(label1.name, label1.parent, label1.attributes)

for item2 in dataset2:
    item1 = dataset1.get(item2.id, item2.subset)
    for ann1 in item1.annotations:
        if hasattr(ann1, 'label') and ann1.label is not None:
            new_label, _ = labels2.find(labels1[ann1.label].name)
            ann1.label = new_label
        item2.annotations.append(ann1)

dataset2.export(path, format, save_images=True)
```

Probably, such merging mode or transform could be a nice feature request.

**Comment by fgabel** [comment]
Ok, thanks a lot, this makes sense.
