### ISSUE TITLE
CLI displaying help or version performance 

### ISSUE THREAD

**Issue by sstrehlk** [openvinotoolkit/datumaro#269]
Long processing of informative functions, like displaying help message or version.

**Steps to reproduce:**
Run
```datum -h```
or 
```datum --version```

**Expected result:**
Informative answer should be in relatively short, not annoying time (less than 0.5sec). For example for pip, pytest, numpy, tensorflow, pycocotools displaying version takes less than 0.3 sec and often less than 0.2sec. 

**Current result:**
Displaying CLI help message or version takes more than 3 sec. 

```
for i in {1..5}; do time datum --version; done
0.1.8

real    0m3.391s
user    0m3.281s
sys     0m1.127s
0.1.8

real    0m3.408s
user    0m3.246s
sys     0m1.166s
0.1.8

real    0m3.478s
user    0m3.368s
sys     0m1.114s
0.1.8

real    0m3.452s
user    0m3.353s
sys     0m1.103s
0.1.8

real    0m3.504s
user    0m3.379s
sys     0m1.133s
```

**Comment by zhiltsov-max** [comment]
Will be resolved by #146
