### ISSUE TITLE
Failed to import module: 'tf_detection_api_format.converter.py' when running

### ISSUE THREAD

**Issue by ipesanz** [openvinotoolkit/datumaro#287]
Hello,

CVAT is running. I'm installing datumaro to convert existing annotations

Environment: `Anaconda`. Just for CVAT but also, the one with TF installed. Same behaviour on both
Installation: `pip install datumaro`
Running with:
- `datum`
- `python -m datumaro`

The program is not crashing, but a warning is raised when starting the program.

`2021-06-09 12:53:20,470 WARNING: Failed to import module 'tf_detection_api_format.converter.py': Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'`

Any idea / recomendation on how to fix it?

**Comment by zhiltsov-max** [comment]
Hi. As the error suggests, I can assume there is no TensorFlow package available in the python environment. Try to run 
`pip install tesnorflow  # or tensorflow-gpu`.

**Comment by ipesanz** [comment]
I agree. Now I see that you tag tensorflow as an optional package... so makes sense a warning is raised and not required via pip
[ I have several tensorboard and other DL packages, but not tensorflow one ]
