### ISSUE TITLE
Segmentation - missing class objects

### ISSUE THREAD

**Issue by yotamint** [openvinotoolkit/datumaro#29]
I'm missing a single class each time I annotate an image with polygons (enabled z order).
Environment used is via docker.

Scenario:
4 classes: a, b, c, d.

![image](https://user-images.githubusercontent.com/18282808/93180289-9c917480-f73f-11ea-97da-68a41e392308.png)

a - top left, b - top right, c - bottom right, d - bottom left (the annotation was done using this order).

I've exported the data via Segmentation mask 1.1.

SegmentationObject png:
![image](https://user-images.githubusercontent.com/18282808/93180456-d95d6b80-f73f-11ea-82ae-e0f6043ff661.png)

But, every time a class is missing in SegmentationClass png:
![image](https://user-images.githubusercontent.com/18282808/93180512-f2feb300-f73f-11ea-874b-a9f5daf05935.png)

**Comment by zhiltsov-max** [comment]
@davodogster, AFAIK, such a training should be possible with masks in the `TFRecord` format, but in CVAT polygons are not converted to masks by default. You can do:
```bash
# export the task as Datumaro project, unzip, cd
# check readme.md
datum project transform -t polygons_to_masks -o transformed
datum project export -p transformed -f tf_detection_api -- --save-images --save-masks
```

**Comment by davodogster** [comment]
@zhiltsov-max Thank you - that code works
