### ISSUE TITLE
Converting COCO with segmentation to VOC not working as expected

### ISSUE THREAD

**Issue by ophir-oneview** [openvinotoolkit/datumaro#329]
Hello, Thanks for the project :) .

I am new here so maybe I am doing something wrong.
But when I am trying to convert the COCO dataset to the VOC dataset it won't work as expected.

This happens when the coco annotations have a segmentation key with polygons (not RLE).
Those annotations aren't converted to the VOC dataset and just disappeared.

**How to reproduce:**
I am using this CLI command:
`datum convert -i coco_instances -if coco -f voc -- --save-images`
On the coco assets in:  `datumaro/tests/assets/coco_dataset/coco_instances`

This creates the COCO to VOC dataset. 
But image b.jpg has two annotations with segmentation one with RLE and the other with a polygon.
The annotation with the RLE was converted to VOC segmentation but the other one not. (getting image inside SegmentationClass and SegmentationObject with only one annotation)   

Will like to know why this happens and if there is a solution to it
Thanks :)

**Comment by zhiltsov-max** [comment]
Hi, this is more or less intended - polygons are not converted automatically to masks. To obtain the results you want, you need to do:

```bash
datum import -i coco_instances/ -if coco -o proj/
datum transform -t polygons_to_masks -p proj/ -o proj_masks/
datum export -f voc -p proj_masks/ -- --save-images
```

**Comment by ophir-oneview** [comment]
Thanks, It looks that it works.
Just need to change -if to -f in the import command:
`datum import -i coco_instances/ -f coco -o proj/`
