### ISSUE TITLE
cvat_format/extractor type casting value to float, causing issues

### ISSUE THREAD

**Issue by maitrai-maka** [openvinotoolkit/datumaro#395]
We have a text type attribute for a bounding box label in CVAT. The values for this attribute are all digits some of which start with zeros. Ex: 0012345, 0123456, 1234567, etc.

We are using datumaro to automatically do some checks on the annotations imported from CVAT. It looks like the extractor for CVAT is trying to typecast all imported numeric [attribute values to float](https://github.com/openvinotoolkit/datumaro/blob/6a2022ed467c7557fb2055c143452bc4ca7f6e86/datumaro/plugins/cvat_format/extractor.py#L96). This is causing an issue for us since this removes the leading zeros automatically from the value, changing user input.

Is there any reason behind typecasting the the attribute value to float? Can this typecasting step be deleted. If required a user can always do the typecasting later.

**Comment by nmanovic** [comment]
@kirill-sizov , could you please look at the issue?

**Comment by kirill-sizov** [comment]
> @kirill-sizov , could you please look at the issue?

@nmanovic Yes, sure

**Comment by zhiltsov-max** [comment]
> Is there any reason behind typecasting the the attribute value to float? 

Datumaro does not have strong attribute data model yet, where value ranges and data types could be described, it should be resolved with #144. So the way is how it is implemented now is our best effort in preserving the attribute data types - logical values, numbers and strings. We tried to have everything as string values, but it didn't work very well.

> Can this typecasting step be deleted. If required a user can always do the typecasting later.

I think yes, especially in case of CVAT format. It has attribute type information, which can be utilized even without big changes.

**Comment by maitrai-maka** [comment]
> could you share any details about your dataset checks?

We are doing simple checks on user input like string length (we know this attribute should have 7 digits). Which is failing because because of leading zeros being removed. All failed checks are exported in CSV format, which we use as a reference to make changes in CVAT. 

CVAT has 2 attribute types: `number ` and `text` for undefined user inputs. However, while importing it looks like both the types are being typecast to float without checking the input_type in CVAT xml currently.  So, if a text type  has only digits it is also being typecast into a float. 

>  Is it possible that Datumaro does it for you with `merge`,` stats` and `validate` commands or any other?

We have not used `stats` or `validate` because we could not find examples for these commands. I think it would not matter if we did since, these commands will be executed after the dataset has already been extracted from CVAT xml, by which time data has already been typecast.

> Are you using some custom code for this, which maybe can be shared? 

We are iterating through each dataset_element->label->attribute to carry out checks. 

```
for item in dataset:
    for box in item.annotations:

        # being forced to typecast the attribute value back to string
        #to check length
        if (len(str(box.attributes['text_test'])) !=7):
            print ("Error: Length of user input not 7.")
```

The above snippet will print an error if the attribute is defined as:
```
<attribute>
   <name>text_test</name>
   <mutable>False</mutable>
   <input_type>text</input_type>
   <default_value></default_value>
   <values></values>
</attribute>
```
and value is defined as `0203450`  by  `<attribute name="text">0203450</attribute>`.  Datumaro is converting this `0203450` to `203450.0` .

**Comment by nmanovic** [comment]
@zhiltsov-max , Datumaro should not convert text to a number.
