### ISSUE TITLE
Support Mapilary

### ISSUE THREAD

**Issue by brunovollmer** [openvinotoolkit/datumaro#411]
Hey, 

do you know if somebody is already working on support for Mapilary and if no, could somebody give me a quick start what I need to know to contribute this format?

Thanks

**Comment by zhiltsov-max** [comment]
Hi, we haven't worked on Mapillary support yet, so feel free to contribute it. Probably, you should start with implementing an Extractor for parsing a dataset in this format. Please look at developer documents: 

Contribution guide: https://github.com/openvinotoolkit/datumaro/blob/develop/CONTRIBUTING.md
Info about plugin implementation: https://github.com/openvinotoolkit/datumaro/blob/develop/docs/developer_guide.md#dataset-formats

Segmentation format parser: https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/cityscapes_format.py#L144-L214
Segmentation format tests: https://github.com/openvinotoolkit/datumaro/blob/develop/tests/test_cityscapes_format.py#L28-L98
