### ISSUE TITLE
How do I remove images without annotations?

### ISSUE THREAD

**Issue by davodogster** [openvinotoolkit/datumaro#42]
Hi, how do I remove images without annotations?
I tried datum project filter -m i+a, but I don't know what to put for the -e param.
This might work datum project filter -m i+a -e 'item/annotation[label!="dswfyhsdyf8"]' .. but the images are not carried over to the subproject (empty directory).

Also, how do I pass a list of images to exclude from the project? (e.g half annotated images/poorly annotated images that I don't want to use for train/val)

**Comment by zhiltsov-max** [comment]
Hi, to remove annotation-less images you need to use `datum project filter -m i+a -e '/item/annotation'`. You won't see images in the output directory, there are only image paths saved in annotations instead. Images will be copied to the output directory on export with `datum project export -f <any> -- --save-images` parameter (BTW, there are filtering options in `export` command too).

You can also check the resulting dataset with `filter --dry-run`.

**Comment by davodogster** [comment]
obj_train_data and train.txt are empty when I do the export as yolo (using the filtered project as the input path). obj.data and obj.names have information in them.
