### ISSUE TITLE
delete the segmentation but keep the bounding box

### ISSUE THREAD

**Issue by DP1701** [openvinotoolkit/datumaro#452]
Hello all, 

I have a dataset that is in coco format and contains segmentations and bounding boxes (see image below). I want to delete the segmentation from the JSON file but keep the BBox information. Do I need to use the filter option for this or a transform operation?

![image](https://user-images.githubusercontent.com/68444979/132482746-31af9909-3acc-4fef-9fac-64ffe7207cea.png)

**Comment by zhiltsov-max** [comment]
Hi. If I understand correctly, what you need to do is replace the "segmentation" annotation fields with "[]". I can suggest few options how to do this.

1. Manually by a simple script or text editor. This will work if there are filled "bbox" values in the file. The script can be the following:
``` python
import json

with open('path/to.json') as f:
  d = json.load(f)

for ann in d.annotations:
    ann["segmentation"] = []

with open('path/to.json', 'w') as f:
  json.dump(d, f)
```

2. With Datumaro:
``` bash
datum import -i path/to.json -f coco_instances -o original_proj
datum transform -p original_proj -t shapes_to_boxes -o boxed_proj
datum export -p boxed_proj -f coco_instances
```
