### ISSUE TITLE
How to convert mask png file to a supported format by CVAT?

### ISSUE THREAD

**Issue by s3298230** [openvinotoolkit/datumaro#51]
Hi,

I have a requirement to import a 3rd party mask dataset into CVAT as polygon for review - The mask sample is attached

Can you advise which steps should I take to convert it into CVAT supported format (such as : segmenetation mask 1.1) using datumaro?

![image](https://user-images.githubusercontent.com/2621517/99217411-90429a00-280a-11eb-8358-20b016ed8213.png)

**Comment by zhiltsov-max** [comment]
Hi, you can find an example here:
https://github.com/openvinotoolkit/datumaro/tree/develop/tests/assets/voc_dataset/SegmentationClass

Format specification is here: https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_manager/formats/README.md#segmentation-mask-import

**Comment by s3298230** [comment]
Thanks for your quick response :) 
As for the Segmentation Mask Import format, it requires both "merged class masks", which I believe is my attached sample above, and "merged instance masks", which I am missing. 
Can we generate the "merged instance masks" from the "merged class masks" ?

**Comment by zhiltsov-max** [comment]
Instance masks cannot be generated from class masks, that's why they are required. However, you can use only class masks - then, a single color will produce a single polygon, or a group, if there are several parts.

**Comment by s3298230** [comment]
> Instance masks cannot be generated from class masks, that's why they are required. However, you can use only class masks - then, a single color will produce a single polygon, or a group, if there are several parts.

Thanks for your information. My issue is resolved and I am able to view the mask in CVAT now

**Comment by 7777-web** [comment]
Hello. Please I have a question. I need to annotate  images on cvat and I’m asked to submit as mask png. How do I do that?

**Comment by zhiltsov-max** [comment]
@7777-web, export in ["Segmentation Mask" format](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/format-voc/#segmentation-mask-export) in CVAT. It will export the annotations as PASCAL VOC masks.

**Comment by 7777-web** [comment]
I’m using a windows laptop
