### ISSUE TITLE
Images missing after merging two datasets

### ISSUE THREAD

**Issue by DP1701** [openvinotoolkit/datumaro#542]
Hello all,

I am trying to merge two datasets using the merge command, but unfortunately this is not successful. 

The following is present:
- Two datasets -> coco_instances
- Both have a different number of images
- In the categories part (anotation file) the names are identical
- Folder structure is the same for both (project can import the datasets without any problems).

Now comes my problem:
With the merge command I try to merge both datasets.

date merge path/to/dataset1:coco_instances path/to/dataset2:coco_instances

I get a folder with the annotation file, a report and a folder for the images. However, this does not contain the images. But in the annotation file there is a path for every single image. I would like to have the images in the folder and remove the paths in the annotation file. How can I do this?

I cannot import the merged dataset (created folder after merge command) into any empty datum project. 

Datumaro version is 0.2

**Comment by zhiltsov-max** [comment]
Hi, thank you for the problem report. Currently, the recommended way to merge datasets in simple cases is using the [`patch` command](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/patch/). This command will also allow to pass options for how to save the results, including an option to `--save-images`. 
``` python
datum patch \ # use either --overwrite or -o output_dir
  path/to/dataset1:coco_instances path/to/dataset2:coco_instances -- --save-images
```

Probably, we need to allow export options in the merge command too, because currently it only produces annotations in Datumaro format. If you need complex merging functionality, consider using API like in the example [here](https://github.com/openvinotoolkit/datumaro/blob/develop/tests/test_ops.py#L231-L263).

**Comment by DP1701** [comment]
@zhiltsov-max thanks for the quick response. The solution works in part for me, as the second dataset contains a few labels that the first does not. 

For example:
1st dataset -> Labels -> [a, b, c]
2nd dataset -> Labels -> [a, b, c, d, e]

Unfortunately I don't see any option now with the patch command to unify this information. 

Is there another option?

**Comment by zhiltsov-max** [comment]
I think, we could extend the `patch` command to support label addition in future. Currently, you can try to use API:

``` python
from datumaro.components.dataset import Dataset
from datumaro.components.annotation import AnnotationType

dataset1 = Dataset.import_from('path1/', 'format')
dataset2 = Dataset.import_from('path2/', 'format')
dataset1.transform('project_labels', 
    set(label.name for label in dataset1.categories()[AnnotationType.label]) |
    set(label.name for label in dataset2.categories()[AnnotationType.label])
) # merge labels
dataset1.update(dataset2)
dataset1.export('path/', 'format', save_images=True)
```

**Comment by DP1701** [comment]
That would be good if the patch command also had the option.
Perhaps a note could be written in the documentation in the merge chapter that the patch command can also merge datasets (incl. export of images).

----


The script merges the annotation files and the images but unfortunately there is an error in the new annotation file. The first dataset contains 23000 images and the other dataset contains 3000 images. If the commands: 

```
datum create
datum add ...
datum info
```

are executed, length should show 26000. In fact, 23000 is shown. I have previously transformed both datasets with 

```
datum transform -t rename ...
```

**Comment by DP1701** [comment]
I think I solved the problem with the reindex option:

```python
dataset1.export(path_for_export, export_format, save_images=True, reindex=True)
```

**Comment by DP1701** [comment]
Hi, does anyone know why the [script](https://github.com/openvinotoolkit/datumaro/issues/542#issuecomment-964085653) no longer works with the latest version? 

I get the error message:

```
TypeError: transform() takes 2 positional arguments but 3 were give
```

**Comment by vinnamkim** [comment]
> Hi, does anyone know why the [script](https://github.com/openvinotoolkit/datumaro/issues/542#issuecomment-964085653) no longer works with the latest version?
> 
> I get the error message:
> 
> ```
> TypeError: transform() takes 2 positional arguments but 3 were give
> ```

Hi @DP1701, Sorry for late response.

In the current version, you should provide keyword arguments rather than positional arguments to give options to the transform such as

- (before)
```python
dataset1.transform('project_labels', 
    set(label.name for label in dataset1.categories()[AnnotationType.label]) |
    set(label.name for label in dataset2.categories()[AnnotationType.label])
) # merge labels
```

- (after)
```python
dataset1.transform('project_labels', 
    dst_labels=set(label.name for label in dataset1.categories()[AnnotationType.label]) |
    set(label.name for label in dataset2.categories()[AnnotationType.label])
) # merge labels
```

The full script that I can succeed to run is as follows.

```python
from datumaro.components.dataset import Dataset, DatasetItem
from datumaro.components.media import Image
from datumaro.components.annotation import AnnotationType, Label
import numpy as np


dataset1 = Dataset.from_iterable(
    [
        DatasetItem(
            id=f"cat_{i}" if i % 2 == 0 else f"dog_{i}",
            media=Image.from_numpy(data=np.zeros(shape=(32, 32, 3), dtype=np.uint8)),
            annotations=[Label(label=i % 2)],
        )
        for i in range(10)
    ],
    categories=["cat", "dog"],
)
dataset2 = Dataset.from_iterable(
    [
        DatasetItem(
            id=f"car_{i}" if i % 2 == 0 else f"bus_{i}",
            media=Image.from_numpy(data=np.zeros(shape=(32, 32, 3), dtype=np.uint8)),
            annotations=[Label(label=i % 2)],
        )
        for i in range(10)
    ],
    categories=["car", "bus"],
)

dataset1.transform(
    "project_labels",
    dst_labels=set(label.name for label in dataset1.categories()[AnnotationType.label])
    | set(label.name for label in dataset2.categories()[AnnotationType.label]),
)  # merge labels
dataset1.update(dataset2)
dataset1.export("path/", "imagenet", save_media=True)
```
