### ISSUE TITLE
Reading MOT dataset with seqinfo produces 0-based indexing in frames

### ISSUE THREAD

**Issue by maartenvds** [openvinotoolkit/datumaro#560]
According to the MOT data format spec, "All frame numbers, target IDs and bounding boxes are 1-based" (quote from https://github.com/dendorferpatrick/MOTChallengeEvalKit/tree/master/MOT#data-format). If this claim is correct, there is a bug in mot_format.py.

When testing the CVAT tool, which uses datumaro, I failed to import a MOT dataset with an error "ValueError: Unknown internal frame id -1\n". To debug, I installed CVAT in developer mode (with VS code) and found two issues that lead to the cause of this error, where one affects this repository. In mot_format.py on line 147 (latest develop branch) there are the following lines:

```
for row in csv.DictReader(csv_file, fieldnames=MotPath.FIELDS):
    frame_id = int(row['frame_id'])
    item = items.get(frame_id)
```
Since ```items``` contains frame ids that start with zero, the item with id zero never gets accessed in this loop because frame_id starts with 1 when mot annotation files is loaded. Also, a possible overrun can occur when frame_id equals the length of the sequence (which is possible since its base-1).

My suggested fix:

```
for row in csv.DictReader(csv_file, fieldnames=MotPath.FIELDS):
    frame_id = int(row['frame_id']) - 1 # one based frame ids
    item = items.get(frame_id)
```

**Comment by zhiltsov-max** [comment]
Hi, thank you for reporting the problem! As I see, we already subtract 1 in [the CVAT format handler](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_manager/formats/mot.py#L37).

**Comment by maartenvds** [comment]
Yes I use a seqinfo file. I also reported a bug on the CVAT repo that is related this this one https://github.com/openvinotoolkit/cvat/issues/3940 (I included a description of the .zip file I used). Since datumaro returned zero indexed item ids, regardless of my suggested fix, the -1 in CVAT format handler is wrong and also contributed to this problem. But indeed its a good thing to review the indexing logic. However, it would be nice if this issue got fixed as soon as possible.

**Comment by zhiltsov-max** [comment]
> Yes I use a seqinfo file.

Then, probably, the fix should be done here: https://github.com/openvinotoolkit/datumaro/blob/develop/datumaro/plugins/mot_format.py#L125-L126

We should just start from 1 instead of 0.

**Comment by maartenvds** [comment]
> We should just start from 1 instead of 0.

That also works and does not require modifications to the CVAT tool.
I implemented the following to test your suggestion:

```
if self._seq_info:
            for frame_id in range(1, self._seq_info['seqlength'] + 1):  # base-1 frame ids
                items[frame_id] = DatasetItem(
                    id=frame_id,
```

And it works!

Shall I make a PR for this?

**Comment by zhiltsov-max** [comment]
Glad to hear this.

> Shall I make a PR for this?

Yes, it would be great!
