### ISSUE TITLE
Does it handle of Images with same Names in two separate Datasets?

### ISSUE THREAD

**Issue by Bilal-Yousaf** [openvinotoolkit/datumaro#59]
Hi,

Could you please confirm if I take two coco datasets as input and output their merged dataset in coco format?
Would this library handle the datasets if both have images with same names?

**Comment by zhiltsov-max** [comment]
Hi, Datumaro tries to merge dataset items with same names. If you want to avoid this behaviour, you can, for example, rename items in a dataset with `rename`, `reindex` and `id_from_image_name` transforms:
```
datum project transform -t rename -- -e '|regex|replacement|' # to rename by regex, python syntax
datum project transform -t reindex [-- --start 10] # to assign sequential integer ids like 10, 11, ...
datum project transform -t id_from_image_name # to use image names as ids instead of existing ids
```
