### ISSUE TITLE
Error use target project path as self._root_dir

### ISSUE THREAD

**Issue by jenhaoyang** [openvinotoolkit/datumaro#603]
https://github.com/openvinotoolkit/datumaro/blob/add81ddb59502362fa65fa07e5bc4d8c9f61afde/datumaro/components/project.py#L1576

this cause **UnexpectedUrlError: The source path is expected to be a directory in the project root** Error

Reproduce:
```
 datum add -f coco  -r annotations/instances_default.json ../a
```

**Comment by zhiltsov-max** [comment]
Hi, please use the `import` command for sources outside the project directory (i.e. `datum import -f coco -r annotations/instances_default.json ../a`). The `add` command is supposed to be used with project-local directories to avoid file copying.

**Comment by jenhaoyang** [comment]
> Hi, please use the `import` command for sources outside the project directory (i.e. `datum import -f coco -r annotations/instances_default.json ../a`). The `add` command is supposed to be used with project-local directories to avoid file copying.

**Comment by zhiltsov-max** [comment]
Hmm, it's an interesting idea. However, doing this would enforce users to navigate into the project directory, which is not always convenient - for example, when you're working with multiple projects simultaneously, or just doing things somewhere else. With the `-p/--project` parameter we can be anywhere and specify the project location correctly. From my point, it is better to show better error message, pointing to the `import` command.
