### ISSUE TITLE
Filter by specific labels and remove specific categories

### ISSUE THREAD

**Issue by DP1701** [openvinotoolkit/datumaro#605]
Hello all, 

I have modified my dataset (coco instances) with the filter option to keep certain labels in the dataset. So images that contain the objects and are marked with a box in the image. I have executed the following command:

```
datum filter -m items+annotations -e '/item/annotation[label="Excavator" or label="Dump truck" or label="Concrete mixer"]'
```
If I execute the command: 

```
datum info
```

 before filtering, I get the following result:

![result_1](https://user-images.githubusercontent.com/68444979/148054095-efeb29ba-03f3-4c80-ad2d-ea6bd57f0970.png)

If I execute the command again after filtering, I get this result:

![result_2](https://user-images.githubusercontent.com/68444979/148054190-4b6c5cbd-3582-4cad-a946-b9879dc1bcc0.png)

As you can see, the number of items has been reduced but the categories have remained the same. When I search for the other 10 labels in the XML structure with the --dry-option, I don't find them either. In the JSON file, the annotations for the unwanted images have also been removed. But all 13 category names remain in the JSON file. 

![example](https://user-images.githubusercontent.com/68444979/148055695-26cf73d5-e3e6-4ea1-a386-f82c13c1f56b.png)

Do I need to change anything else in the filter command to remove the remaining 10 category names?
Or is this not possible?

**Comment by zhiltsov-max** [comment]
Hi. The `filter` command just filters the annotations, but doesn't affect categories declared in the dataset (if the dataset format allows this). If you want to modify categories, consider using the [`transform` command](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/transform/#built-in-transforms-a-idbuiltin-transformsa) with `project_labels` or `remap_labels` transforms. Both of them allow to remove labels from the dataset:

```bash
datum transform -t project_labels -- -l "Excavator" -l "Dump truck" -l "Concrete mixer"
# or
datum transform -t remap_labels -- -l "Excavator:Excavator" -l "Dump truck:Dump truck" -l "Concrete mixer:Concrete mixer" --default delete
```

**Comment by DP1701** [comment]
@zhiltsov-max  Thank you very much! It works.
