### ISSUE TITLE
transform with resize also changed the image extension from .jpg to .png

### ISSUE THREAD

**Issue by shaojun** [openvinotoolkit/datumaro#606]
Hi,
thanks for the great tool.

I'm using version `0.2.2`, `Ubuntu 20.04.3 LTS on x86`.
I have a small testing `kitti` dataset, mixed with `.jpg` and `.jpeg` with size `1280x720` and `800x600` images files.
I've tried the steps to use `datum`:
```
datum --version
#0.2.2
mkdir datum_proj_real
cd datum_proj_real
datum create
datum import -f kitti ../my_small_kitti_dataset
```
can see:

> Source 'source-1' with format 'kitti' has been added to the project

then do the transform to unify image size:

`datum transform -t resize -- -dw 800 -dh 600`

now checking the subfolder: `source-1` in project folder: `datum_proj_real`, can see all images files are renamed with `.png` extension, and none of them can be opened by image viewer.

I also tried manually rename one of the file's extension from `png` to `jpg`, and still could not be opened with an error popup like not a valid jpg file.

could you help to check?

**Comment by shaojun** [comment]
thanks, does that mean those generated `.png` files are expected behavior here?

**Comment by nmanovic** [comment]
@shaojun , yes, it means. But at the same time it is possible to implement extra parameters for the export operation. Thus it can be a feature request and we are happy to accept contributions in the area.

**Comment by zhiltsov-max** [comment]
Hi, probably, I was wrong about the images. I was able to reproduce the problem. Apparently, it is a result of a several problems, one of which already described in #618 (the problem with file reading).
