### ISSUE TITLE
datum stats and transform with resize failed to run on part of PascalVOC dataset

### ISSUE THREAD

**Issue by shaojun** [openvinotoolkit/datumaro#607]
hi,

I'm using version `0.2.2`, `Ubuntu 20.04.3 LTS on x86`.

I've downloaded part of officical `PASCAL VOC` dataset: **VOCtrainval_11-May-2012.tar**, untar it can see **17125** pictures under `voc20212/JPEGImages`.

I created a `datum project` and run `datum stats`:

```
datum import -n voc2012 -f voc ../dataset_data/pascalVOC/VOCtrainval_11-May-2012/VOCdevkit/VOC2012/
#Source 'voc2012' with format 'voc' has been added to the project
datum stats
```
But got below error:

> /home/shao/.local/lib/python3.8/site-packages/datumaro/components/operations.py:1031: RuntimeWarning: overflow encountered in uint_scalars
>   M2 = m_a + m_b + delta ** 2 * count_a * count_b / (count_a + count_b)
> /home/shao/.local/lib/python3.8/site-packages/datumaro/components/operations.py:1033: RuntimeWarning: overflow encountered in uint_scalars
>   count_a + count_b,
> /home/shao/.local/lib/python3.8/site-packages/datumaro/components/operations.py:1035: RuntimeWarning: overflow encountered in uint_scalars
>   M2 / (count_a + count_b - 1)
> 2022-01-07 15:09:15,977 INFO: Writing project statistics to 'statistics.json'

For keep moving, I tried to resize for uniform all images size:

`datum transform -t resize -- -dw 800 -dh 600`

it ran a while, then see error:

> 2022-01-07 15:20:45,303 INFO: Transforming...
> Killed

could you check?

**Comment by zhiltsov-max** [comment]
Hi, I was able to reproduce and fix both problems. The warnings are correct, but they should not really affect the pixel mean and std stats, though. Thank you for reporting the issues!
