### ISSUE TITLE
Pytest generate many permission error

### ISSUE THREAD

**Issue by jenhaoyang** [openvinotoolkit/datumaro#612]
Running github action pytest generate many permission error even only modify doc

for example:

CI #1404 in pull reqiest #608 **add more example for add command**

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\datumaro\\datumaro\\temp_test_can_find_project_in_project_dir-s6pipwkr\\.git\\index'

**Comment by zhiltsov-max** [comment]
Opened an issue https://github.com/gitpython-developers/GitPython/issues/1395
