### ISSUE TITLE
explain command cannot find the model 

### ISSUE THREAD

**Issue by beste-d** [openvinotoolkit/datumaro#721]
When I try to infer an image with a model included in the project using the command 'explain', I get the error : 
**AttributeError: 'Tree' object has no attribute 'models'**

However, when I check the project info I see that the model is successfully added to the project, and the model can also produce annotations with 'model run' command 

Any help will be appreciated.
![Screenshot from 2022-07-28 11-34-46](https://user-images.githubusercontent.com/110161019/181460641-5c25f77e-f7fb-4347-9ab3-efc14f912b03.png)

**Comment by vinnamkim** [comment]
Hi @beste-d, sorry for the late response. We found that it is a bug and made a fix for it. Thanks for your interest in this project.
