### ISSUE TITLE
Patch command producing two .json files

### ISSUE THREAD

**Issue by Testbild** [openvinotoolkit/datumaro#725]
Hello,

I have an odd issue with the patch command (attached you find my annotation files).

The 487instances_default.json file is the one that should be patched. Once with the 193instances_default.json and once with the 83instances_default.json. When using the 193instances it works fine, if I use the 83instances I have again 2 files in the output folder. Both files look the same to me from the classes and so on like the 487instances file and I do not really get an error message. Do you have an idea what this could be?

[Annotations.zip](https://github.com/openvinotoolkit/datumaro/files/9447469/Annotations.zip)

**Comment by zhiltsov-max** [comment]
Hi. The reason might be that the files with such names are imported as
datasets with different subset names (with different number prefixes). To
merge them, try to call the jsons them the same way - eg
"instances_default.json".


вт, 30 авг. 2022 г., 01:36 Testbild ***@***.***>:

**Comment by Testbild** [comment]
Ok suprisingly that worked. Thank you!
