### ISSUE TITLE
Scale images with percentages

### ISSUE THREAD

**Issue by DP1701** [openvinotoolkit/datumaro#728]
Hey, is it possible to scale images and labels with percentages instead of entering a specific resolution? I have images in different resolutions and would like to scale them down by only 50%.

**Comment by zhiltsov-max** [comment]
Hi, there is no such feature yet - only a specific resolution is available for resizing. Could you describe your usecase for such function? Typically, neural networks expect a fixed size input.

**Comment by DP1701** [comment]
Hi @zhiltsov-max, that' s right. The only reason I have for this is to reduce the resolution of the images when storage space needs to be saved and high resolutions are not required.

**Comment by zhiltsov-max** [comment]
Please look at this discussion https://github.com/openvinotoolkit/datumaro/issues/562

**Comment by wonjuleee** [comment]
I will close this with a feature `ResizeTransform` at https://github.com/openvinotoolkit/datumaro/pull/581.
