### ISSUE TITLE
K Fold COCO Dataset

### ISSUE THREAD

**Issue by Testbild** [openvinotoolkit/datumaro#730]
Hi,

this is somehow a question/feature request. I need to make a K Fold with a COCO Dataset. The issue I am struggling is: I need to have a different COCO.json file for each fold (or do I not need this?).

So far it is fairly easy to split the images, but to generate the COCO.json for each fold I have not found a tool yet. Is this possible with datumaturo repo to do this?

I would be expecting to have e.g. 5 folds:

coco1fold.json
coco2fold.json
...
coco5fold.json

**Comment by zhiltsov-max** [comment]
Hi, yes, you can try to use the [`random_split` transform](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/transform/#random_split-transform) like this:

CLI:
```bash
datum transform -t random_split \
  -o dataset_with_folds path/to/coco/dataset/:coco \
  -- -s f1:0.2 -s f2:0.2 -s f3:0.2 -s f4:0.2 -s f5:0.2
```

Python API:
```python
import datumaro as dm
dataset = dm.Dataset.import_from('path/to/coco/dataset', 'coco')
dataset.transform('random_split', splits=[('f1', 0.2), ('f2', 0.2), ('f3', 0.2), ('f4', 0.2), ('f5', 0.2)])
dataset.export('output/dir/', 'coco', save_images=True)
```

**Comment by Testbild** [comment]
Thank you!

Eventually I ended up using this: https://www.kaggle.com/code/ammarnassanalhajali/k-fold-crossvalidation-coco-dataset-generator/notebook as I did not want to make a random split, but yours also worked.
