### ISSUE TITLE
Rename Function  produce an error in Windows

### ISSUE THREAD

**Issue by AbdelsalamHaa** [openvinotoolkit/datumaro#840]
Hi all, 

When I try to use the rename function under transform I get an error. I followed the documentation here 
https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/transform/

I used the following command 
`datum transform -t rename task_72 -- -e '|frame_|task72_|' `

Then I get the following error 
```
'frame_' is not recognized as an internal or external command,
operable program or batch file.
```

I tried with other commands but I keep getting the same error.

**Comment by vinnamkim** [comment]
Hi @AbdelsalamHaa,

Sorry for inconvenience. Our team will look into this problem, but it would be helpful for us if you give me a small subset of your dataset to reproduce your problem. Thanks you!

**Comment by AbdelsalamHaa** [comment]
@vinnamkim Thank you very much for your reply. 
My data is simple data exported from  CVAT with YOLO format. I added the attached folder as a source to my datumaro project using datum add -f yolo task_72. 
[task_72 - Copy.zip](https://github.com/openvinotoolkit/datumaro/files/10918102/task_72.-.Copy.zip)

**Comment by AbdelsalamHaa** [comment]
@vinnamkim @sooahleex 

In case this information is helpful to find the issue, the reindex command is working fine, but it will not really rename the files, it  will generate new files with the name start from the -s parameters.
so I would still need to go to the folder and delete the old files

**Comment by sooahleex** [comment]
Hi @AbdelsalamHaa, Thank you for sharing your dataset. I checked the status of `rename` in `transform`. I tried to check this issue through below commands. 
```bash
datum create
datum add -f yolo task_72
datum transform -t rename task_72 -- -e '|frame_|task72_|'
```
and the `task_72` folder's tree structure is like below before `rename`.
```bash
├── obj.data
├── obj.names
├── obj_train_data
│   ├── frame_000000.PNG
│   ├── frame_000000.txt
│   ├── frame_000020.PNG
│   └── frame_000020.txt
└── train.txt
```
I found that the issue you mentioned in description does not reproduce in my side, but I checked that the `rename` command do not really rename the files, it generate new files as you mentioned above comment like below tree structure. This is the tree structure which I checked only after `rename` command. 
```bash
task_72/
├── obj.data
├── obj.names
├── obj_train_data
│   ├── frame_000000.PNG
│   ├── frame_000020.PNG
│   ├── task72_000000.PNG
│   ├── task72_000000.txt
│   ├── task72_000020.PNG
│   └── task72_000020.txt
└── train.txt
```
Since a project directory is a working directory for processing a series of processes such as `transform`, the contents of that directory may not reflect the final state of the project. You must use `save` or `export` command to reflect the final status of dataset. You could refer this document [how to use datumaro examples](https://openvinotoolkit.github.io/datumaro/docs/user-manual/how_to_use_datumaro/#examples)
I checked the tree structure only one more `export` command after the commands which I mentioned above, the dataset is updated well as you intended. This is the tree structure which I checked after `export` command.
```bash
task_72/
├── obj.data
├── obj.names
├── obj_train_data
│   ├── task72_000000.PNG
│   ├── task72_000000.txt
│   ├── task72_000020.PNG
│   └── task72_000020.txt
└── train.txt
```

If you have more question about this, please let me know.

**Comment by AbdelsalamHaa** [comment]
@sooahleex Hi  Thank you very much for your reply.

I did exactly the same steps you mentioned above but I still get the same issue

```
'frame_' is not recognized as an internal or external command,
operable program or batch file.
```
 
May I know what is the version you are using for datumaro . I run `datum --version` and got my version is 1.0.0 after using `pip install --upgrade datumaro` I still get the same version 1.0.0 

For the export command. After running the export command I get another folder that contains a totally new copy of the data. 
In my case my data is huge around 70 GB, so doing that cause a lot of redundant memory usage.  

Thank you again for your reply and I look forward to your reply. 

Note: 
I'm using the following: 
Windows 11 
python 3.8.16 with anaconda
datumaro 1.0.0

**Comment by sooahleex** [comment]
@AbdelsalamHaa Hi, I think your error is related to the name of data. In my opinion, I think your issue could be occurred due to some of your data does not have `frame_` for the prefix. 
And, I am using the following:
Ubuntu 18.04
python 3.9.15 with anaconda
Datumaro version 1.0.0

**Comment by AbdelsalamHaa** [comment]
@sooahleex 
Thank you for your reply. I found out what is the issue but still the command not working as intended. apparently, the "|" symbol is a special character in the Windows command prompt, and it is used to chain multiple commands together. so to solve the problem I had to add "^" this symbol to consider "|" part of the command. 

so the final command will be as follow
`datum transform -t rename task_72 -- -e '^|frame_^|task72_^|'`

Although this prevented the error from happening the command still not working as intended. after running the command only the frame_ was removed. but it was not replaced. 
Any idea how to solve that. 

Note: 
I'm using the same dataset I shared with you to test these commands.

**Comment by AbdelsalamHaa** [comment]
Hi @sooahleex 
I have finally resolved the issue. It is kinda embarrassing to say but in the end, all I had to do is to replace ' with ". and it solved the problem. 

so instead of running 
`datum transform -t rename task_72 -- -e '|frame_|task72_|'`
I had to run 
`datum transform -t rename task_72 -- -e "|frame_|task72_|"`

I will close this issue. I'm not sure if any documentation need to be update it to avoid this confusion for windows users

**Comment by sooahleex** [comment]
Hi @AbdelsalamHaa Sorry for late response. I checked the issue you mentioned, it is not related to Datumaro issue. You could check this like [this](https://stackoverflow.com/questions/51080215/differences-between-single-and-double-quotes-in-cmd). In the Window command prompt, single quote(') and double quotes(") have different roles when it comes to handling strings and special characters. 
Double quotes are used to define strings that contain spaces or special characters in the command prompt. When you enclose a string within double quotes, the command prompt will treat the whole string as a single argument, including spaces and special characters. This is useful when you want to pass a file path or an argument with spaces to a command or a script, like `mkdir "New Folder"`
On the other hand, In the Windows command prompt, single quotes don't have any special meaning. They are treated as regular characters. Therefore, using single quotes won't have the same effect as using double quotes when dealing with strings containing spaces or special characters. 
Your problem isn't about Datumaro, it's about the rules in the window command. By the way, I would like to update the documentation to reduce confusion among users. Thank you for finding this part!
