### ISSUE TITLE
dataset merge from cvat tasks does not treat each image from 2 videos uniquely

### ISSUE THREAD

**Issue by santhoshkelathodi** [openvinotoolkit/datumaro#853]
I have created 2 coco datasets from 2 videos using cvat. 
Since the images are having same filename for frames from both videos, The merge does not work. Wondering if an option is there to merge with path prefix while merging would solve this issue.
dataset1 = dm.Dataset.import_from('./job1/','coco') #125 images
compute_image_statistics(dataset1)
>
{'dataset': {'images count': 125,
  'unique images count': 125,
  'repeated images count': 0,
  'repeated images': []},
 'subsets': {'default': {'images count': 125,
   'image mean': [100.19872088074985, 94.00044830292754, 91.86856111513269],
   'image std': [48.68377781686017, 49.061841907855886, 50.82771343023279]}}}

dataset2 = dm.Dataset.import_from('./job2/','coco')  #300 images
compute_image_statistics(dataset2 )
>
{'dataset': {'images count': 300,
  'unique images count': 300,
  'repeated images count': 0,
  'repeated images': []},
 'subsets': {'default': {'images count': 300,
   'image mean': [81.45160655341432, 75.45445490944425, 75.49834119591269],
   'image std': [62.61469409144919, 59.270918751098186, 59.57495309334001]}}}

dataset1.update(dataset2)
dataset1.export('./merged/dataset/', 'coco', reindex=True)
compute_image_statistics(dataset1)
{'dataset': {'images count': 300,
  'unique images count': 300,
  'repeated images count': 0,
  'repeated images': []},
 'subsets': {'default': {'images count': 300,
   'image mean': [81.45160655341432, 75.45445490944425, 75.49834119591269],
   'image std': [62.61469409144919, 59.270918751098186, 59.57495309334001]}}}

I found that the merged dataset only has 300 images and it does not include the images from both the videos. I guess that it is due to the same name being present in both the datasets corresponding to the frame sequence.

    "images": [
        {
            "id": 1,
            "width": 1280,
            "height": 960,
            "file_name": "frame_000000.PNG",
            "license": 0,
            "flickr_url": "",
            "coco_url": "",
            "date_captured": 0
        },

**Comment by vinnamkim** [comment]
Hi @santhoshkelathodi,
Thanks for your interests on our project! I'll look at this issue and reply to you as soon as possible.

**Comment by vinnamkim** [comment]
I think your guess that there are items with duplicate IDs in both datasets is correct. To remedy this, we can use Datumaro's `dataset.transform("rename", regex="|frame_(\d+)|target_name_\\1|")` Python API. I left a [Jupyter notebook example link for this](https://github.com/vinnamkim/datumaro/blob/notebook/rename/notebooks/08_rename.ipynb). I think you might get the point from [this example](https://github.com/vinnamkim/datumaro/blob/notebook/rename/notebooks/08_rename.ipynb).

**Comment by santhoshkelathodi** [comment]
@vinnamkim Wonderful. It worked..The notebook is of great help. 

I have one more query about the merge of multiple datasets together. Which is the function corresponding  to the CLI option
datum merge project1/ project2/ project3/ project4/ \
  --quorum 3 \
  -iou 0.6 \
  --groups 'person,hand?,head,foot?'

I find that the merge with the following command gives error even though the datasets are of same type
dataset3 = dm.Dataset.from_extractors(dataset1, dataset2) # ref from 01_merge_multiple_datasets_for_classification.ipynb in GitHub
---------------------------------------------------------------------------
ConflictingCategoriesError                Traceback (most recent call last)
[c:\digi\Project\util\cocosplit\wb.ipynb](file:///C:/digi/Project/AI/util/cocosplit/wb.ipynb) Cell 6 in 1
----> [1](vscode-notebook-cell:/c%3A/digi/Project/AI/util/cocosplit/wb.ipynb#W6sZmlsZQ%3D%3D?line=0) dataset3 = dm.Dataset.from_extractors(dataset1, dataset2)

File [c:\Users\santhosh.kumaran\Anaconda3\envs\DIGI_ENV\lib\site-packages\datumaro\components\dataset.py:892](file:///C:/Users/santhosh.kumaran/Anaconda3/envs/DIGI_ENV/lib/site-packages/datumaro/components/dataset.py:892), in Dataset.from_extractors(env, merge_policy, *sources)
    888 from datumaro.components.merger import get_merger
    890 merger = get_merger(merge_policy)
--> 892 categories = merger.merge_categories(s.categories() for s in sources)
    893 infos = merger.merge_infos(s.infos() for s in sources)
    894 media_type = merger.merge_media_types(sources)

File [c:\Users\santhosh.kumaran\Anaconda3\envs\DIGI_ENV\lib\site-packages\datumaro\components\merger.py:36](file:///C:/Users/santhosh.kumaran/Anaconda3/envs/DIGI_ENV/lib/site-packages/datumaro/components/merger.py:36), in Merger.merge_categories(self, sources)
     34                 categories[cat_type] = source_cat
     35             else:
---> 36                 raise ConflictingCategoriesError(
     37                     "Merging of datasets with different categories is "
     38                     "only allowed in 'merge' command.",
     39                     sources=list(range(source_idx)),
     40                 )
     41 return categories

ConflictingCategoriesError: Merging of datasets with different categories is only allowed in 'merge' command.

**Comment by vinnamkim** [comment]
Would you check `dataset.categories()` of `dataset1` and `dataset2`? `dm.Dataset.from_extractors(dataset1, dataset2)` requires both categories being exactly same.

In this case, you can use `IntersectMerge` like

1) In the latest develop,
```python
dm.Dataset.from_extractors(dataset1, dataset2, merge_policy="intersect_merge")
```

2) Explicitly use `IntersectMerge` with parameters
```python
from datumaro.components.operations import IntersectMerge
iou_thresh = 0.25 # IoU match threshold for segments
groups = [] # A comma-separated list of labels in annotation groups to check. '?' postfix can be added to a label to make it optional in the group (repeatable)
output_conf_thresh = 0.0 # Confidence threshold for output annotations
quorum = 0 # Minimum count for a label and attribute voting results to be counted

merger = IntersectMerge(
    conf=IntersectMerge.Conf(
        pairwise_dist=iou_thresh,
        groups=groups or [],
        output_conf_thresh=output_conf_thresh,
        quorum=quorum,
    )
)
merged_dataset = merger.merge([dataset1, dataset2])
```

**Comment by santhoshkelathodi** [comment]
> vinnamkim



> ```python
> intersect_merge
> ```
I found that the categories were not the same.
The Option 2 works well... Thank you very much for the reply....My issue is resolved now...
With Option 1 that I think would be solved in the next version I assume.
---------------------------------------------------------------------------
ConflictingCategoriesError                Traceback (most recent call last)
[c:\digi\Project\AI\util\cocosplit\wb.ipynb](file:///C:/digi/Project/AI/util/cocosplit/wb.ipynb) Cell 7 in 2
      [1](vscode-notebook-cell:/c%3A/digi/Project/AI/util/cocosplit/wb.ipynb#X10sZmlsZQ%3D%3D?line=0) # Merge when the categories are not matching 
----> [2](vscode-notebook-cell:/c%3A/digi/Project/AI/util/cocosplit/wb.ipynb#X10sZmlsZQ%3D%3D?line=1) dataset4 = dm.Dataset.from_extractors(dataset1, dataset2, merge_policy="intersect_merge")
      [3](vscode-notebook-cell:/c%3A/digi/Project/AI/util/cocosplit/wb.ipynb#X10sZmlsZQ%3D%3D?line=2) dataset4.export('[./ws_merge2/export](https://file+.vscode-resource.vscode-cdn.net/c%3A/digi/Project/AI/util/cocosplit/ws_merge2/export)', 'coco', reindex=True, save_media=True)

File [c:\Users\santhosh.kumaran\Anaconda3\envs\DIGI_ENV\lib\site-packages\datumaro\components\dataset.py:892](file:///C:/Users/santhosh.kumaran/Anaconda3/envs/DIGI_ENV/lib/site-packages/datumaro/components/dataset.py:892), in Dataset.from_extractors(env, merge_policy, *sources)
    888 from datumaro.components.merger import get_merger
    890 merger = get_merger(merge_policy)
--> 892 categories = merger.merge_categories(s.categories() for s in sources)
    893 infos = merger.merge_infos(s.infos() for s in sources)
    894 media_type = merger.merge_media_types(sources)

File [c:\Users\santhosh.kumaran\Anaconda3\envs\DIGI_ENV\lib\site-packages\datumaro\components\merger.py:36](file:///C:/Users/santhosh.kumaran/Anaconda3/envs/DIGI_ENV/lib/site-packages/datumaro/components/merger.py:36), in Merger.merge_categories(self, sources)
     34                 categories[cat_type] = source_cat
     35             else:
---> 36                 raise ConflictingCategoriesError(
     37                     "Merging of datasets with different categories is "
     38                     "only allowed in 'merge' command.",
     39                     sources=list(range(source_idx)),
     40                 )
     41 return categories

ConflictingCategoriesError: Merging of datasets with different categories is only allowed in 'merge' command.

**Comment by vinnamkim** [comment]
Hi @santhoshkelathodi,
Could you please provide your small sampled datasets to us if there is no problem?
I think it would be very helpful to fix the option 1 in the next version.

**Comment by santhoshkelathodi** [comment]
@vinnamkim It is an absolute pleasure to do so for Datumaro...I have made a sample notebook cell as below:

#--------------------------------------------------------------------------------------
import datumaro as dm

dataset1 = dm.Dataset.import_from('./person/','coco_instances')
dataset2 = dm.Dataset.import_from('./car/','coco_instances')

dataset1.transform("rename", regex="|frame_(\d+)|dataset1_frame_\\1|")
dataset2.transform("rename", regex="|frame_(\d+)|dataset2_frame_\\1|")

print("dataset1 item ids:", [item.id for item in dataset1][:10])
print("dataset2 item ids:", [item.id for item in dataset2][:10])

# Merge when the categories are not matching 
# Option 1: This option gives Error
dataset3 = dm.Dataset.from_extractors(dataset1, dataset2, merge_policy="intersect_merge")

# Option 2: Works
from datumaro.components.operations import IntersectMerge
iou_thresh = 0.25 # IoU match threshold for segments
groups = [] # A comma-separated list of labels in annotation groups to check. '?' postfix can be added to a label to make it optional in the group (repeatable)
output_conf_thresh = 0.0 # Confidence threshold for output annotations
quorum = 0 # Minimum count for a label and attribute voting results to be counted

merger = IntersectMerge(
    conf=IntersectMerge.Conf(
        pairwise_dist=iou_thresh,
        groups=groups or [],
        output_conf_thresh=output_conf_thresh,
        quorum=quorum,
    )
)
dataset4 = merger.merge([dataset1, dataset2])
#--------------------------------------------------------------------------------------
 and the corresponding dataset is attached 
[person_car.zip](https://github.com/openvinotoolkit/datumaro/files/10987205/person_car.zip)

**Comment by vinnamkim** [comment]
Thank you @santhoshkelathodi!
