### ISSUE TITLE
Broken links in README.md and contributing.md

### ISSUE THREAD

**Issue by frostasm** [openvinotoolkit/datumaro#971]
Issue branch `develop`

### Broken links in `README.md`:

All links to `https://openvinotoolkit.github.io` are broken.

### Broken links in `contributing.md`:

**Related sections**
- ~~[Design document](https://github.com/openvinotoolkit/datumaro/blob/develop/docs/design)~~
- ~~[Developer manual](https://github.com/openvinotoolkit/datumaro/blob/develop/api/api/developer_manual.html)~~

**Comment by vinnamkim** [comment]
Hi @frostasm,
Thanks for your interests on our project!
We will look into this issue ASAP.

**Comment by vinnamkim** [comment]
We will change all links to point to this domain soon: https://openvinotoolkit.github.io/datumaro/latest.

**Comment by JihwanEom** [comment]
Hi @frostasm, we just merged #972  to resolve the reported issue. Thank you for bringing it to our attention.
